openstack-cluster:
  nodeGroups:
    - name: default-md-0
      machineCount: 2
      machineFlavor: dep-l2.tiny

  nodeGroupDefaults:
    machineFlavor: dep-l2.tiny

  addons:
    ingress:
      enabled: true
      nginx:
        release:
          values:
            controller:
              service:
                # *.prod-mgmt.nubes.stfc.ac.uk
                loadBalancerIP: "130.246.80.233"

    monitoring:
      kubePrometheusStack:
        release:
          values:
            defaultRules:
              additionalRuleLabels:
                cluster: management
                env: prod
            prometheus:
              prometheusSpec:
                externalLabels:
                  cluster: management
                  env: prod
              ingress:
                hosts:
                  - prometheus.prod-mgmt.nubes.stfc.ac.uk
                tls:
                  - hosts:
                      - prometheus.prod-mgmt.nubes.stfc.ac.uk
                    secretName: tls-keypair
            grafana:
              ingress:
                hosts:
                  - grafana.prod-mgmt.nubes.stfc.ac.uk
                tls:
                  - hosts:
                      - grafana.prod-mgmt.nubes.stfc.ac.uk
                    secretName: tls-keypair
            alertmanager:
              enabled: true
              ingress:
                hosts:
                  - alertmanager.prod-mgmt.nubes.stfc.ac.uk
                tls:
                  - hosts:
                      - alertmanager.prod-mgmt.nubes.stfc.ac.uk
                    secretName: tls-keypair
