stfc-cloud-openstack-cluster:
  openstack-cluster:
    cloudCredentialsSecretName: prod-management-cluster-cloud-credentials

    addons:
      etcdDefrag:
        release:
          values:
            schedule: 11 08 * * * # smearing the time for defrag job 11:08am daily
