apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-deployed-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/stfc/cloud-deployed-apps.git
    targetRevision: david-epa-branch
    path: clusters/staging/davidepa
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: staging-david-epa-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=invalid"]
  generators:
    - list:
        elements:
          - name: argocd
            chartName: argocd

            # NOTE: each chart needs a valuesFile for this to work
            # so create one for each chart - even if its empty

            # argocd and all dependencies use the same file "argocd-setup-values.yaml"
            namespace: argocd
            valuesFile: ../../../clusters/staging/davidepa/argocd-setup-values.yaml
            secretsFile: ../../../clusters/staging/davidepa/secrets/apps/argocd.yaml

          - name: logging
            chartName: logging
            namespace: logging-system
            valuesFile: ../../../clusters/staging/davidepa/logging.yaml
            secretsFile: ../../../clusters/staging/davidepa/secrets/apps/logging.yaml

          - name: cert-manager
            chartName: cert-manager
            namespace: cert-manager
            valuesFile: ../../../clusters/staging/davidepa/argocd-setup-values.yaml

          - name: cluster-api-addon-provider
            chartName: cluster-api-addon-provider
            namespace: clusters
            valuesFile: ../../../clusters/staging/davidepa/argocd-setup-values.yaml

          - name: ingress-nginx-external
            chartName: ingress-nginx-external
            namespace: ingress-nginx-external
            valuesFile: ../../../clusters/staging/davidepa/ingress-nginx-external-values.yaml

          - name: longhorn
            chartName: longhorn
            namespace: longhorn-system
            valuesFile: ../../../clusters/staging/davidepa/argocd-setup-values.yaml


  syncPolicy:
    # Don't remove everything if we remove the appset
    preserveResourcesOnDeletion: true

  template:
    metadata:
      name: "{{.name}}"
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: "https://github.com/stfc/cloud-deployed-apps.git"
        targetRevision: david-epa-branch
        path: "charts/staging/{{.chartName}}"
        helm:
          valueFiles:
            - '{{.valuesFile | default "../../../clusters/_shared/dummy.yaml"}}'
            - secrets://{{ .secretsFile | default "../../../clusters/_shared/dummy.yaml"}}

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.namespace}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true

      # ignore outofsync issues with longhorn CRDs with "preserveUnknownField"
      # https://github.com/argoproj/argo-cd/issues/6401#issuecomment-854995249
      ignoreDifferences:
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        jsonPointers:
        - /spec/preserveUnknownFields

  templatePatch: |
    {{- if eq .name "manila-csi" }}
      spec:
        ignoreDifferences:
          - group: rbac.authorization.k8s.io
            kind: ClusterRole
            name: manila-csi-openstack-manila-csi-controllerplugin
            jsonPointers:
              - /rules
          - group: rbac.authorization.k8s.io
            kind: ClusterRole
            name: manila-csi-openstack-manila-csi-nodeplugin
            jsonPointers:
              - /rules
    {{- end }}
