stfc-cloud-logging:
  includePrometheusRules: true
  opensearchCredentials:
    username: writer-staging
  fluent-operator:
    operator:
      disableComponentControllers: fluentd
    fluentd:
      crdsEnable: false
    fluentbit:
      output:
        loki:
          enable: false
        opensearch:
          logstashPrefix: kube_logs_staging_david-epa
          # staging worker opensearch for now, with plans to move it to prod/olaf
          host: opensearch.staging.nubes.stfc.ac.uk
          port: 443
