creation_rules:
  - unencrypted_regex: "^(apiVersion|metadata|kind|type)$"
    key_groups:
      - age:
          # Temporary key for ArgoCD
          - age1cpv0ejrvuv2hslsy4nq66zwkmkqrn4c3km66lwfkmcyqpxr8v4wsfajuck 
          
          # Access Keys
          # Prod Access Key
          - age1cq92796c46d06s43t079xc89exe4vd52rh30c9mcafmne62dxyhqrupl4l