stfc-cloud-logging:
    opensearchCredentials:
        password: ENC[AES256_GCM,data:4D5gHVRNzQwp4qEX0sXFVUr1ej4=,iv:vifYF1CgPnPvMHSbt5Bh49DZIJ1GqT5Pd60sS55NOPM=,tag:9J6zOZV8vlu4nC1Cyd6pyQ==,type:str]
sops:
    age:
        - recipient: age1cpv0ejrvuv2hslsy4nq66zwkmkqrn4c3km66lwfkmcyqpxr8v4wsfajuck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLM0VvNDVldklLZWxHNkZ4
            ZEdWVllGT3hhSmZFTW5hL3JLMUZVSzl5Tlc4ClZDN2xLQnNqbUx0VG9vWFRjYXk3
            ZElLNDdPNlY5UjNBaCtLdStLcHZkckkKLS0tIDB1UVI2Qks2RVBNNlFFSG9PUFp1
            SEJnSU9oUGt6YzZJVmJveWhOUi82cEkKjJFXxG/l0ADcClpdvLqoxajBaQK2ThrZ
            1kGjtXMmT5FCBCs/CchEeb6CEgXHXy0bnGcTIfUzrSIvmsM9TCd8kg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cq92796c46d06s43t079xc89exe4vd52rh30c9mcafmne62dxyhqrupl4l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYzdJSy9PWERDQ0pDUnZm
            a1pVaWF1dXBLK3JWQnlDY2F4TEtkdWw2U0JnClVvYWRTa3pYazJYRTkyT3o2UDgv
            UnNDTFRYNWJST3ZJaFNBMS9ablZrNk0KLS0tIGNEUk96L3JsakZteEIwcGNxcVJO
            UExQejY0TWpobGhSUStURGo1NnhndkkKYBco3d+R8YguCMBs4ADezED1APnwj7O9
            fofpauBovh/iKZMy6NvrUcuhYQj7vUGozMcnv9jF8Ht3z1x3PFeVQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-26T12:44:50Z"
    mac: ENC[AES256_GCM,data:AyYXQEG2pmiHPgIJYLKHeZgwzHHfB5Q7ItGD1CIw5YuxR079meJE/GwmlAdSmKw6K4Q6pi7GJSb8lEwr/I6mYqYt001y0rMP4djmNmb+iJ/TG77/DCOVgSq9MIholnAycHRLI24pJHDKWAjh6t2QVPl99rMA9S2PbYdqECS+LN4=,iv:k1I5LZTVmVvTy3jFnfsjzbk0sYn6ZUf3KZMmoFGEiTg=,tag:0QbqReh2T7NXSq4V2o2H3w==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
