stfc-cloud-openstack-cluster:
    clouds:
        openstack:
            auth:
                auth_url: ENC[AES256_GCM,data:x8d+Lu9ZebqN/qeZ3VxZv+4gJ+S9AtAPow7rkFHcbt0X2Ri7mg==,iv:KLzXBbJgelGtX+oKw06fh/ypfnSfzdO1z82T159GdeI=,tag:mwwOub9ejbU0O/JNIa0Rlw==,type:str]
                application_credential_id: ENC[AES256_GCM,data:D5L8EMRe/8BSJ2o1ow/d9O5Pg/Kk4ESiFJQfikJnWZk=,iv:lRfqFyDcsmOq2TwLpxDPl4DeJoaTlBWKr7icUym1Q1Q=,tag:wCHoEGLgzwCDNWXLoOkFxQ==,type:str]
                application_credential_secret: ENC[AES256_GCM,data:FF7U0fohgvfcBCmj10sbTJuzZKtU0d5hlTuuK5DTz9BV5sXMWMyy4Nmw5ZLzr0krHIxupIYOQ4npu3vuNpIsLeFTK6oNDmFhXQqCJVnJYNioU8hu51k=,iv:gCUa7kdx73kyiYO972rbigS1E/OqfjSDUcvb9gGODUE=,tag:QJWAtpz4hPA+QsrLjGe1uA==,type:str]
                project_id: ENC[AES256_GCM,data:BPAfpGXlg0bTLOavBz0Rgk65Nj9TRQE2HGLnm2LpnjA=,iv:93q+A2/EOuYNlezaSLdrnQVDJwEN6Xn36I0C9eTjHWc=,tag:zW/caag/25SYljFpat8i4w==,type:str]
            region_name: ENC[AES256_GCM,data:czrEzm0YLJ/u,iv:6+jEN5DjXUXZUzRr1ryC1uWHdPc+vbGQYirUXTrNWto=,tag:hPZigue7s+9VDZSmxqBsww==,type:str]
            interface: ENC[AES256_GCM,data:o7ccZUQk,iv:dym9U6oRkC+5UBrUXFGTYqymM1WDCMCv3YqplGtvPb0=,tag:/6xdIA1T2TOtxooLR+ttWA==,type:str]
            identity_api_version: ENC[AES256_GCM,data:1w==,iv:ttbUzuQRwKR84nay+OWpbtq5taed1rzod/uhiiZglNU=,tag:d8x9nVJgEgGarI5iZRZJoA==,type:int]
            auth_type: ENC[AES256_GCM,data:P2FcXQi5TZ1Fa+n5jTVo0AfW7g1y6fA=,iv:1j9IbWINyWXRwhWgJEaT7uHNRp8CMwAkel4n6v3BBCA=,tag:9bT+lM0DBYex0uv07CG1Qw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tgfg98jddwc2crr869aa9phe9ufflnyya4t3mcltqsmcvca0k46q2m04se
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPKys2TjRrSlFXRS9aN2tq
            L29tSjJKREJabExIL3hlcTdodURCZXk3ZlZvCjAwQTFjZnFDWm5NTjVTZ1Y0cWlk
            ZUNycjZJNGk2dk5Vc25rY2s0cGJGZXcKLS0tIHpydEV6VGlzVU1pY2JJSXRrT2t0
            MGduaU8wOE1LUkozZnQwQ0ZOcnNTclEKmfXvmbsLvQvJ3KMFzsPfBQEwlOPL4E0N
            WhXENaG2fV648StPUZs5ecYayWTPDSOeDijOhu1OCg0/sd8milBQyg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hsll27prywydttq7dtnqtdnu2jpr8zhaulx00l7n4pqmxkhr55vspqmj6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTk1tblRFYmxUY0FMeTR4
            dEhmajJESk11dVhkWDBhZUI0ejJXRS9VM0hNCmw5ZFlzMlVhdHMyU0RPL2t0ZlBN
            ejFVSFdOK0RMVEl5a0s4TmNPUmYvZVEKLS0tIDFWRXNxUWJPNWMwdFl5KytOcy9l
            RWt5cFBwaE1YSUZlSE9JbURyNWxlbEUKL64AvQiY97/6EVoY+8RRYJLOUZ9dV9i0
            dRQ6cPM3suav8Wyug50eKGMVwiX1VhaINh9t3Tnhb7QSqG0oK9G6pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-13T15:02:41Z"
    mac: ENC[AES256_GCM,data:a0l/nPVny9BV8aJe+rPgca5zALQ2UMzW1NR5BepX7w+NfVLiU+g/2ciIekmZQuDKPtzgqQdPfu7rXMTm/dg9+IuZl1F1lm35Hg8sQ5M4cVZxdOzsCzmfcmrFbopaIvh8l7PAxBYnpUNNzHVxWxuVADa9o3FXVoY7NtkxF4bnv5g=,iv:Ydy7IxWPu7oQNMnJEisfcjVz1JB59+4fM1SJg4iYaLc=,tag:IYMj3Oz5GzcOTV96SpxnlA==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.8.1
