stfc-cloud-openstack-cluster:
    clouds:
        openstack:
            auth:
                auth_url: ENC[AES256_GCM,data:Xjj2bm2qbf8KYxiWJjC1ogdzJB3gxWg9lme2HfdAMfW1,iv:7pxPnrMs/jh+AYeYKCm+KZa32EMBVK7MesC23TuFvVI=,tag:vil7qfhztHDJqlnSsj8vlg==,type:str]
                application_credential_id: ENC[AES256_GCM,data:NZYiLRDcVMQnEWCT0dYPK21kjlIFXJiDwsMNtyqefF0=,iv:/YnfzTKu1X3uMwF4Hult5gFwPncFB2WEOkBxcKQKtbk=,tag:StcWPOLL4UZLr7HU29M7wA==,type:str]
                application_credential_secret: ENC[AES256_GCM,data:IULdwc4v02BvyV6mXNVlFwTq4Lln7Yukxu/4+Qh3IJuYp1i+J4oFpLFm98y2tYsfMYHf+VrMpFt0nUu8McOOqpbX4B5e31wXLYyQUaEmWDlnzRBzJ9k=,iv:VTlp/9nXr5GopWn0nk5A1giMtagrvfYGXmUxuTr48u4=,tag:zTxgL4HEzzPEfFCJEFIdLg==,type:str]
                project_id: ENC[AES256_GCM,data:a3O/r2xNbzwQZVt9ehyVgM4CWyJYkXYrmvRJmEpCXJE=,iv:p5B2Yy3ZAP5viETn18pZUYTKR382h+/W0DgLyoZh4Ts=,tag:SIA2g/9aovwvkOkxeWwsYg==,type:str]
            region_name: ENC[AES256_GCM,data:/bZMRqtNGpYg,iv:yQ8sYUwdAsPJPKZjtXVmAhAb92mO49OBPgjp4VcBd9c=,tag:/QtrS8ls+ewK2NK0wGSWcw==,type:str]
            interface: ENC[AES256_GCM,data:XTMAifQb,iv:w6LaYRsKx4AZnJtVT3J5Laocfiy2L2XO4dqpwjZ4HmA=,tag:krGFpo2/EmRHVn/LirimTg==,type:str]
            identity_api_version: ENC[AES256_GCM,data:Mg==,iv:qEFTepuXEXdDg8BIQZwOD5uY9IG16nO7GpZT+h/5qYo=,tag:Ik9+R/RLB/nDhkBWrBiAcQ==,type:int]
            auth_type: ENC[AES256_GCM,data:5r/uOT5VI632s17cFSbXHY0h0Kf11IM=,iv:9iTd8o67ZBD2EW0doaKl1WdfPUtQgvcIckXVO4UjFHs=,tag:jB8ewZWnoSkC4iuXgbd5fQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hsll27prywydttq7dtnqtdnu2jpr8zhaulx00l7n4pqmxkhr55vspqmj6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZUhCNmZJRWV1eXB0dkNQ
            c1UrNkJJK2FNM0MzSGpVSzJtb3RWNy85WjFJCnlHZ1ZBMjEyMVlUc0dMdHNsRExZ
            bFVMMWczbm5yYStRMWNFNW9rSlJ4NWcKLS0tIFdhT2xwTk5hQnlTbGRPRGJwMnZW
            VFVZQ3k4ZEhYVVB5WUtEVVoycExjS3MKVkRpwNVLHrdQEU50FS4KeCs/CKv5ppJC
            EkcsDu9lV44Zv3m6PgZI5lM3p0iJLR0tcQsshpXzNaHT74a6iVVo3w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1p9rynn6rcdfhx0kdks0sh5drjrjg857cuujapu04m9a2r0zarq6stdha6c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTld6VVVRNVd3aWpjK1o3
            MWlxRThUY2wycVE1VXprcWJXOW5teEdrNEJBCjVDV3BOaVQzM0Z4eVc4UEN2MWJV
            QldtaTFJT1U0MlhDOGN6T05GMFQrWFUKLS0tIHVkNE1HZnVaWk03UTlkZkphdVhv
            N0d2QU9BU2pPd0JjT25PNjd1bGZVSlEKO1yBeypB8a34Q7S3ppawVYIO8/D/S02d
            MFW59WkB09g9eGlMdmKdL6l4I8na7njBuXuK6gFt4AghbvmdrcSTcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-01T11:06:06Z"
    mac: ENC[AES256_GCM,data:RJi8iwcCflsw6YcohOuZy/+PEenecYm3ywrK1quK0+d2cSp25pTb/O4ZSJjCz54jSBU6HGenMMH+AaBd2+mCTQ6oXVovBjAyZ7gjd+e04wgJGFunfn6oN+5tXkc5ebWjYdpJnZR0bOIxEWRS3oEizoUAsTJtSbBc51YIdYOV0lA=,iv:EGu+13ih+iPj65ER8/Ob7Qwq6xZdULmSLzaxZrjd6Pk=,tag:d0IRxZToQc1MRZW4xbV9IA==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.8.1
