stfc-cloud-openstack-cluster:
    openstack-cluster:
        addons:
            monitoring:
                kubePrometheusStack:
                    release:
                        values:
                            grafana:
                                extraObjects:
                                    - apiVersion: v1
                                      kind: Secret
                                      metadata:
                                        name: grafana-iris-iam-creds
                                      spec:
                                        stringData:
                                            client_id: ENC[AES256_GCM,data:JljiL2xOMrlGf3IMq1TaJ/gxq87gzv0jL/0vMhqD+UA0pk1p,iv:cEUls3Ws/1fpM5/LAkW7Yf79JOKGhee2Ks6CZHPTl3s=,tag:QisheU76ADyQ3BLLFea9dw==,type:str]
                                            client_secret: ENC[AES256_GCM,data:cBwrERsPfXrKRckMGh5RpL6XfXmIGzSy0T/+E67Acm639tstukj2+0ed77eaENPyGYw/H6myPWh0RJebnM1P5y6F5dadjwd6t/KnoUcT+rO0F+k7BTI=,iv:8yFemfjqwRE9gtDwy8/Oouj9KTJbSWMBzdmlobmQJZ4=,tag:ce2/gQtyJVjYpUG4yR4wBQ==,type:str]
                            prometheus:
                                extraSecret:
                                    name: ENC[AES256_GCM,data:Q/RJwTWMa5zdlQ==,iv:kMVINkIiJFWZ6cK+4guSnTWE9m1QCXPHuJXhQgJfs9c=,tag:voLZYpa87fsGqFHcEcYTPw==,type:str]
                                    data:
                                        auth: ENC[AES256_GCM,data:XvCQCGQhB7CcJuwDf+XGuuWDLwC4iZvgiWoUAfbr2eJB8Nfk6wz0hA4WoA==,iv:n9Nx/iBsbjeynZd2MXqCOKig8gaJg2g46DQF68Pn9Xk=,tag:Q+7+QC7Eik9T6rGx2E3oFQ==,type:str]
sops:
    age:
        - recipient: age1tgfg98jddwc2crr869aa9phe9ufflnyya4t3mcltqsmcvca0k46q2m04se
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibzJ0b3d2TWdmTUdYcTBj
            Y3E2VE9YekR5ZFB5VlRtUkI3eXExcFpDa0Q0CjU5Ni82TW8rQ3BJQ2ZwdytBMWJl
            cjhpelRNSW5uSXNyV2tZbTJqellpOTgKLS0tIGNSV2llWnlyYTYwd3VjL21CZ2xE
            cXNOZWJrdzVPOXgzYThIbFkwMkxIdXcKUFpoGqN5VmYAaGBYm8OOir1ok7GBpY+C
            NxOgGsETj0FAtPOaKNWWeSEv2NnymWq9eETNle2tSmt1jQfVnoQSBQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hsll27prywydttq7dtnqtdnu2jpr8zhaulx00l7n4pqmxkhr55vspqmj6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzeFMwaTRSRFQwcWlYUHN1
            ZDRJaFNSTEpuRHFYaGhFNHRiSUVscnl6SFdBCjE5VU50RG1RdURaZDZYVGpGTGoy
            ZDZDVUk0Y3ZUak9tKzVzTUxRSVl1RlEKLS0tIElsZGhUUXBQTXZ0bnNEOS9nVW5n
            UHgrWWIyKzUyeE85NE9zRS9UaHVGMDAKKSOD1s2mOdJIuXQnuc4EklaIACoBfHPc
            sGz9T/vE9iOnh+M+/cr3maFK1UVSFtoOrta1gRczdRjjJAXY9u5buw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-30T15:59:10Z"
    mac: ENC[AES256_GCM,data:2DapsCQw2U1O4kKkpQ/kwDZ6FauMS303ckVCY+rDMcH4TM4Znw1KeoBsbuItCR8u71WgLOdRiFp96R9DVRwRtN3JnjMK/vcZFe/aVifwDB99Gkj+MBsbNLHSUs7sqIkDArP85gESzOtbMuHKpNL0r/qOMDKUH4aXKajzJjKMTOo=,iv:yldLxtjAuqYF7dDvmaIrlrD3NpVttTH6zMGGr1UNwAs=,tag:nd7HSxiyj5Z8FgrOdT29Dw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
