creation_rules:
  - unencrypted_regex: "^(apiVersion|metadata|kind|type)$"
    key_groups:
      - age:
        # Temporary key for ArgoCD
        - age1wdf2g6m5hpultm2qg824saycmph22fg9ar7yscda7fwt8kals5kq4atu5s

        # Access Keys
        # Staging Access Key
        - age1hsll27prywydttq7dtnqtdnu2jpr8zhaulx00l7n4pqmxkhr55vspqmj6l
