creation_rules:
  - unencrypted_regex: "^(apiVersion|metadata|kind|type)$"
    key_groups:
      - age:
          # Staging Worker Cluster - ArgoCD Access Key (Temporary)
          - age1wafyp6k09cm8nmftypg9cv4gaqz305teaw06t77a7vaju0spt5fsk8rd9v

          # Access Keys
          # Staging Access Key
          - age1hsll27prywydttq7dtnqtdnu2jpr8zhaulx00l7n4pqmxkhr55vspqmj6l
