creation_rules:
  - unencrypted_regex: "^(apiVersion|metadata|kind|type)$"
    key_groups:
      - age:
          # Staging Management Cluster - ArgoCD Access Key (Temporary)
          - age1kkmt80g0cq4uud8gtxwa9p9y4l9nwa2mk8rlqp29sgvkku99evesc0gfsl

          # Access Keys
          # Staging Access Key
          - age1hsll27prywydttq7dtnqtdnu2jpr8zhaulx00l7n4pqmxkhr55vspqmj6l
