stfc-cloud-logging:
    opensearchCredentials:
        password: ENC[AES256_GCM,data:qS4suaPSxH6gYyK/+1GcNnLkbf0=,iv:mJBBAw8PwqYEwzQw1TLww/jgVd54K3/QG7pakA/W5P0=,tag:N0v1pW6ndDvoYauwur1vUQ==,type:str]
sops:
    age:
        - recipient: age1g9eweaxtpfsxpagxklaru08j5a9gpdqjnhyjzav6hsfyvq0h0aaszq6vky
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuM1JUOWJYaUtyNDJqL3Bk
            eTlNWGJ5UVF4L0syOFFaaUEzQ3JlcmZmV2hzCi85eXlDYVZxdnRhMWtQNUgxU00w
            bXNqYmNFTm12V1NwYVQ1TEdNSDNQY0UKLS0tIDd6Rnc0RGgraHpndTVLOTFBOFlJ
            aEdnWitTT0c3aXZsaEJ4T0pEN3hiUTQKaDMYy6MlQ1HAMV4RMK3jhkwKoBz5e0P4
            AOvxjxaJlYjteweStLLr7sljwAvIhWmpDaZjFB1lSztThgGjxJ+rKg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hsll27prywydttq7dtnqtdnu2jpr8zhaulx00l7n4pqmxkhr55vspqmj6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLc2U0emZXdzcxK0tRRmFG
            MmhISWJQRVFkQ09BY3k1N1BMNjVhc1IxRUc4ClNtOFlDL0ZheDgvK09KRER0Zm1U
            cHJnZTBMejdxRUNiMDlEbHllWFRaTkkKLS0tIFBndmk2UUsvUGEzV2p0THJVcFVu
            NXVXZHBQTVUxRmZmcks3RHNRYWNab3cKAUkoUcpgqDuPPp7eKoPsJnc0H+RK8tYB
            vJbEU7nuaDk3TuiaL7pUXK0VNwk6AjnoXWkRB5LOZoMAF+3aQNPmBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T18:13:31Z"
    mac: ENC[AES256_GCM,data:bx7+Yl/HBvvogEQcbW9/hoDKwgDR6dSzAJ/o9SyAtbpPUP0CHDX29sYtwby1AzHlqvhuQwi5FtgnJZlWhyJ6zhnClCBUXgGSoPE+2wWRRca75wyyMp5GLjqJb4BV2Maf6+iGTAt9KHfkvyxYei2myB/KwIndq8SJ3n7rMaPa+bo=,iv:7rnJtclyOKcFuY3J1ys0y1ZvCA5ye9X2UyWIKVBmOpE=,tag:TYPS/ov2MmUBXenWnZYZCg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
