stfc-cloud-logging:
    opensearchCredentials:
        password: ENC[AES256_GCM,data:qS4suaPSxH6gYyK/+1GcNnLkbf0=,iv:mJBBAw8PwqYEwzQw1TLww/jgVd54K3/QG7pakA/W5P0=,tag:N0v1pW6ndDvoYauwur1vUQ==,type:str]
sops:
    age:
        - recipient: age1wafyp6k09cm8nmftypg9cv4gaqz305teaw06t77a7vaju0spt5fsk8rd9v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaNHdoeXlWZC9UVTBqQ0hG
            Z2VWemJyNGZVM1NHZ0cyUERNYVd4NnVqSFJnCjFVNDBWYUF0L1NFeXg2OUIwVm5l
            aVpBazZCTzQyMjNCeTZacmJ5czhUNzQKLS0tIGpreld3OVByUXoyUkdHcXZrSlZJ
            WFQ2VExvL0crUUp4czJ1eGh3K0EyUWcKEY7ftYjCrHdaxKnzIoZQmk0gGRElrfEN
            GUO86HVjuPHfhBdexWoNniQPTuIYPFBV1hG3XCLjMMFXwiicneQdjg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hsll27prywydttq7dtnqtdnu2jpr8zhaulx00l7n4pqmxkhr55vspqmj6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMnFYWWtpZis1VDQ0bkxE
            QTVEVnZxaEU0Yk9OQ1hsVWNGOEJFQ3RlcFY4CjZxaGdqWUp0am5DZGRuK0F2blEx
            ZG1lSmFiOWd1dTVKRndSVDFvYVQ3RWMKLS0tIDRpWUcyNWFkd2cvNjlRbVJZZGxt
            UG11S21xS0lNbmJ2WE1rck1wRDQraVUKZyAtHEBq9S+xECXzveokUOKEUcX/pMEl
            MnzI+8WqIN25F+4pSahpB3x7fhU+H10C5uKDdxfr5r1xMq05HqMXyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T18:13:31Z"
    mac: ENC[AES256_GCM,data:bx7+Yl/HBvvogEQcbW9/hoDKwgDR6dSzAJ/o9SyAtbpPUP0CHDX29sYtwby1AzHlqvhuQwi5FtgnJZlWhyJ6zhnClCBUXgGSoPE+2wWRRca75wyyMp5GLjqJb4BV2Maf6+iGTAt9KHfkvyxYei2myB/KwIndq8SJ3n7rMaPa+bo=,iv:7rnJtclyOKcFuY3J1ys0y1ZvCA5ye9X2UyWIKVBmOpE=,tag:TYPS/ov2MmUBXenWnZYZCg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
