stfc-cloud-logging:
    opensearchCredentials:
        password: ENC[AES256_GCM,data:qS4suaPSxH6gYyK/+1GcNnLkbf0=,iv:mJBBAw8PwqYEwzQw1TLww/jgVd54K3/QG7pakA/W5P0=,tag:N0v1pW6ndDvoYauwur1vUQ==,type:str]
sops:
    age:
        - recipient: age1wdf2g6m5hpultm2qg824saycmph22fg9ar7yscda7fwt8kals5kq4atu5s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMk16c2hyR3dWSlpzanlR
            RzJwR3IyU1AxbEJvWmJ4am5Cd1ZleHlsMEhFCnMxY25LNkRYQWJkSnlCbk96NVdV
            TURvalZQTDkyU3lBbVJVZWVjV3Q4YlUKLS0tIFJVWGsxQXBFMkVtdGZCRkVNWGZx
            UlF2cG1xVU5KTmtTaVloaC9VOXZlZUUK/+JXQca4IViqVgL/JPz471W/vOsTKpvp
            Ydd3zxr9jJoC5sYM1mWEYvczxrZ6ya8SKinw/ir8zQpGURIvPYyJ0A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hsll27prywydttq7dtnqtdnu2jpr8zhaulx00l7n4pqmxkhr55vspqmj6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUFgydUtiK3h5RDBxS0R3
            OFkrN0QrWWhET2hueGtVYUNCcmdzTFNGQ0dFCkxFQi9nSkd3cW05ZTlPR1RWd1VC
            L0R1SkdUNDUxTzloeENJQjVBN05QRWcKLS0tIE8rR29mSWFYWkFLWE1FbXFTRktX
            WDhwa3lOY1FJQUYzZmtoWEhyR2NRTU0K38kFKowD/F3oGMOynOoxRouVdUdtQBRN
            jIMroERSJf3wHrrHo2lEClSfLwxFeXiBLvjdMo1XqRCXdGmd8Vwkjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T18:13:31Z"
    mac: ENC[AES256_GCM,data:bx7+Yl/HBvvogEQcbW9/hoDKwgDR6dSzAJ/o9SyAtbpPUP0CHDX29sYtwby1AzHlqvhuQwi5FtgnJZlWhyJ6zhnClCBUXgGSoPE+2wWRRca75wyyMp5GLjqJb4BV2Maf6+iGTAt9KHfkvyxYei2myB/KwIndq8SJ3n7rMaPa+bo=,iv:7rnJtclyOKcFuY3J1ys0y1ZvCA5ye9X2UyWIKVBmOpE=,tag:TYPS/ov2MmUBXenWnZYZCg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
