{{-.Values.internal.basicAuth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: internal-basic-auth
  namespace: monitoring-system
type: Opaque
stringData:
  # htpasswd format - generate with: htpasswd -nb <user> <password>
  credentials: {{ required "basicAuth.credentials is required when not using existingSecret" .Values.basicAuth.credentials | quote }}
{{- end }}