apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-deployed-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/stfc/cloud-deployed-apps.git
    targetRevision: folder_flows
    path: clusters/david-dev/management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true

---

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
    name: management-apps
    namespace: argocd
spec:
  generators:
    - list:
        elements:
        - name: "argocd"
          chartName: argocd
          # NOTE: each chart needs a valuesFile for this to work 
          # so create one for each chart - even if its empty
          # argocd and all dependencies use the same file "argocd-setup-values.yaml" 
          valuesFile: ../../../clusters/david-dev/management/argocd-setup-values.yaml
          namespace: argocd

        - name: "cert-manager"
          chartName: cert-manager
          namespace: cert-manager
          valuesFile: ../../../clusters/david-dev/management/argocd-setup-values.yaml
        
        - name: cluster-api-addon-provider
          chartName: cluster-api-addon-provider
          namespace: clusters
          valuesFile: ../../../clusters/david-dev/management/argocd-setup-values.yaml

  template:
      metadata:
        name: '{{name}}'
        namespace: argocd
      spec:
        project: default
        source:
          repoURL: "https://github.com/stfc/cloud-deployed-apps.git"
          targetRevision: folder_flows
          path: "charts/dev/{{chartName}}"
          helm:
            valueFiles:
              - values.yaml
              - "{{valuesFile}}"
        destination:
            server: https://kubernetes.default.svc
            namespace: "{{namespace}}"
        syncPolicy:
          automated:
            prune: false
            selfHeal: true
            allowEmpty: true

---

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: management-clusters
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: "https://github.com/stfc/cloud-deployed-apps.git"
        revision: folder_flows
        files:
        # grab all infra values for all clusters in environment
        - path: "clusters/david-dev/*/infra-values.yaml"
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{path.basename}}-cluster'
      # All applications need to go into the ArgoCD namespace
      namespace: argocd
    spec:
      project: default
      destination:
        namespace: clusters
        server: https://kubernetes.default.svc
      source:
        repoURL: https://github.com/stfc/cloud-deployed-apps.git
        targetRevision: folder_flows
        path: charts/dev/capi-infra
        helm:
          releaseName: '{{path.basename}}'
          valueFiles:
            # Bring in values that are specific to this application
            - '../../../{{path}}/{{path.filename}}'
            # Bring in secrets that are specific to this application
            - 'secrets://../../../secrets/{{path[1]}}/{{path[2]}}/api-server-fip.yaml'
            - 'secrets://../../../secrets/{{path[1]}}/{{path[2]}}/app-creds.yaml'
  
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true