creation_rules:
  - unencrypted_regex: "^(apiVersion|metadata|kind|type)$"
    # All developers can access / edit secrets on dev
    key_groups:
      - age:
          # Dev Worker Cluster - ArgoCD Access Key (Temporary)
          - age1x0t4j6qxqy42usha0u658r4f5p5d48y8knfuchyu2sc2rywtacgsryp0t6

          # PERSONAL ACCESS - FOR DEV ONLY

          # David Fairbrother Desktop
          - age1acqcungzwkt807d3jt94ngtdt0vhk9kec4ps4a22cpaah57jw4xsl7q4xc
          # David Fairbrother Laptop
          - age1h3dmygqf4v6jg3nxk5sr9jkp27w3q83sqnqxdd5n92xf3w6fs5kshakrxn
          # Anish Mudaraddi
          - age12khufkd7z25eqgpjjyy0zcrq6kpjxzekmff5zhq7q54tajm4e58qul35x0
          # Ramzi Jalili
          - age16fufeddr0arrns268526gxethxgkh3g0euf8cn37kuwfmq3h23psutz4q8
          # Ryan Whiting
          - age1a8e4gxw67kp27s3hssfxyem3e8jwaha3huz0sttfngeu60pk5pxqkfpg3d
          # Kalibh Halford
          - age1drky6caal0j2x58yzpw9tyflcpdpmcjqy8nss7zfvspszg0xfpdsyzu8s4
          # Abdul Aziz
          - age1m57vjw60dpr02ghka8kh2xlqsa0ggxauau2y488zdh89vu760qgqh8lcge
          # George Matthews
          - age1cmq75nz6rxancqlj7g7r2pum8c9xlznuetslmjmthk2g9p4flgdqz0tv8g
