apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-deployed-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/stfc/cloud-deployed-apps.git
    targetRevision: main
    path: clusters/staging/management
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: management-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: "argocd"
            chartName: argocd

            # NOTE: each chart needs a valuesFile for this to work
            # so create one for each chart - even if its empty

            # argocd and all dependencies use the same file "argocd-setup-values.yaml"
            valuesFile: ../../../clusters/staging/management/argocd-setup-values.yaml
            namespace: argocd

          - name: "cert-manager"
            chartName: cert-manager
            namespace: cert-manager
            valuesFile: ../../../clusters/staging/management/argocd-setup-values.yaml

          - name: cluster-api-addon-provider
            chartName: cluster-api-addon-provider
            namespace: clusters
            valuesFile: ../../../clusters/staging/management/argocd-setup-values.yaml

  syncPolicy:
    # Don't remove everything if we remove the appset
    preserveResourcesOnDeletion: true

  template:
    metadata:
      name: "{{name}}"
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: "https://github.com/stfc/cloud-deployed-apps.git"
        targetRevision: main
        path: "charts/staging/{{chartName}}"
        helm:
          valueFiles:
            - "{{valuesFile}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: management-clusters
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: "https://github.com/stfc/cloud-deployed-apps.git"
        revision: main
        files:
          # grab all infra values for all clusters in environment
          - path: "clusters/staging/*/infra-values.yaml"
  syncPolicy:
    preserveResourcesOnDeletion: true

  template:
    metadata:
      name: "staging-{{path.basename}}-cluster"
      # All applications need to go into the ArgoCD namespace
      namespace: argocd
    spec:
      project: default
      destination:
        namespace: clusters
        server: https://kubernetes.default.svc
      source:
        repoURL: https://github.com/stfc/cloud-deployed-apps.git
        targetRevision: main
        path: charts/staging/capi-infra
        helm:
          valueFiles:
            # Bring in values that are specific to this application
            - "../../../{{path}}/{{path.filename}}"
            # Bring in secrets that are specific to this application
            - "secrets://../../../secrets/{{path[1]}}/{{path[2]}}/api-server-fip.yaml"
            - "secrets://../../../secrets/{{path[1]}}/{{path[2]}}/app-creds.yaml"

      syncPolicy:
        automated:
          # Remove anything that isn't in the helm chart output
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
