stfc-cloud-openstack-cluster:
  openstack-cluster:
    cloudCredentialsSecretName: staging-management-cluster-cloud-credentials
    registryMirrors: { docker.io: ["https://staging.dockerhub.stfc.ac.uk/v2/"] }

    controlPlane:
      machineFlavor: dep-l2.tiny

    nodeGroups:
      - name: md-0
        machineCount: 2
        machineFlavor: dep-l2.tiny

    nodeGroupDefaults:
      machineFlavor: dep-l2.tiny

    addons:
      monitoring:
        kubePrometheusStack:
          release:
            values:
              prometheus:
                prometheusSpec:
                  externalLabels:
                    cluster: management
                    env: staging
                route:
                  main:
                    enabled: true
                    hostnames:
                      - prometheus.staging-mgmt.nubes.stfc.ac.uk
                    parentRefs:
                      - name: internal-gateway
                        namespace: envoy-gateway-system
                        sectionName: https
              grafana:
                grafana.ini:
                  server:
                    root_url: https://grafana.staging-mgmt.nubes.stfc.ac.uk
                route:
                  main:
                    enabled: true
                    hostnames:
                      - grafana.staging-mgmt.nubes.stfc.ac.uk
                    parentRefs:
                      - name: internal-gateway
                        namespace: envoy-gateway-system
                        sectionName: https

              alertmanager:
                enabled: true
                route:
                  main:
                    enabled: true
                    hostnames:
                      - alertmanager.staging-mgmt.nubes.stfc.ac.uk
                    parentRefs:
                      - name: internal-gateway
                        namespace: envoy-gateway-system
                        sectionName: https

      etcdDefrag:
        release:
          values:
            schedule: 10 08 * * * # smearing the time for defrag job 10:08am daily
