stfc-cloud-openstack-cluster:
  openstack-cluster:
    machineSSHKeyName: k8s-staging
    cloudCredentialsSecretName: staging-management-cluster-cloud-credentials
    registryMirrors: { docker.io: ["https://staging.dockerhub.stfc.ac.uk/v2/"] }

    controlPlane:
      machineFlavor: dep-l2.tiny

    nodeGroups:
      - name: md-0
        machineCount: 2
        machineFlavor: dep-l2.tiny

    nodeGroupDefaults:
      machineFlavor: dep-l2.tiny

    addons:
      etcdDefrag:
        release:
          values:
            schedule: 10 08 * * * # smearing the time for defrag job 10:08am daily
