stfc-cloud-logging:
    opensearchCredentials:
        password: ENC[AES256_GCM,data:mftdReAdZu2PNnPJ61ESPHXg0Ic=,iv:3i0S1iBxGHTGelYjqSyC9B64LCpQbj6+a9WRbyYGghI=,tag:m5Vak5gil4+IQJMrMFUTNQ==,type:str]
sops:
    age:
        - recipient: age1tgfg98jddwc2crr869aa9phe9ufflnyya4t3mcltqsmcvca0k46q2m04se
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNjlTVS9mbGFpT1B4Ri8r
            bzU2WWR4QU05T0hENlIwbXUyZmdXdTMwdlY0Ck5uY0RZUVJnU1RNMXE3bUhoMXAr
            Uis3SlFkY2o4a2NLcjZqNTFjMW4yVzgKLS0tIFVHb2FpTHpqYXBOMFl4R1NqRlJX
            b2MyenBXQmxJU1FXcTNncUtOWWd6RmsKoF2DKpfDhdinUemhpPE18PknDOvLBKed
            YBXLuJ/ZIDwSYI2waob7Q0h8bebgMUR/SIWuPJA+1vQqbDr/1ILQLA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hsll27prywydttq7dtnqtdnu2jpr8zhaulx00l7n4pqmxkhr55vspqmj6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZG4vVGUvWlR1b0kxVWpJ
            bGI5TXZxblByWHNudVlpbjFmWXlnZTBjMGtFCjZ2Z0JkYkM5bTR4N1l6cUJwRThI
            dy9IYm9UblRWamdhNUlwM3Z1dHFKd2MKLS0tIFlCUDNuV21VcElCUGxUS1VyVFgz
            SlZnaTFsejVHeWNsbUdqaFB3aUYwbFkKzmSRsXpsBFHEPoz7MoInpvx04XlnB3RY
            uI7EU7l0dQseho/GyboUS/XI0Ncpx8ByYRd5/qlZUcvyWVLnXMoh0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T18:11:09Z"
    mac: ENC[AES256_GCM,data:2ueFswoZzUGS8QUsg4PHTSN/N+tWdCNS3DL9M6HXh3WDKf4qx4G7XtL7vRC19QdqKhRKiDzwIwhrRx5+Aigyoax2KV8PV5MEjkQLGH5S8GnpAw6RduTQvxkjh8kIJWlFkuKusR2Oka3CmtRHF33a2mODA08+D/vkJSBuLHfW0v0=,iv:DpHtbAmVjTlI36ESbkOY/3+Atz76fWKBu34Nr8GTtmU=,tag:fju2myWt4Zqmd83G2M0EKQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
