stfc-cloud-logging:
    opensearchCredentials:
        password: ENC[AES256_GCM,data:Pfb4Ab/qD4vdFZuJbUGuWUVoklk=,iv:8+WCpn7B5g9/g6o77Bq42gKRyxr9DRCt80x0YJnElCc=,tag:TMUft7HFLRrx5GKsY159dw==,type:str]
sops:
    age:
        - recipient: age1p9q4tzawn9jh3evsgkuslklm2d4zhwhyhtcfls7n62a8cdpv8vqq7t9hqv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUjA0eDlNanZsRmJHR1FZ
            Q1JjdkJoN1F1TFlWSXRqSGZWdTI5TUM3eFgwCnAvcUJVSFZnbFBacVFvWmluaXpD
            WHF6NFVJMS9SZjloSU1oOUxDdWxrM1UKLS0tIHhyakh3bVQrNGFFTmhWVzBHbk9J
            bkYyRis1WE1adGZCNTRMbWMyZXBqM3cK0E3hzbfxut9Zt2U9FN9ripXJ1FMWVw6f
            AiWELMppWSRRnVJJ47dZcaR8TO58S4YP1gb6IBsea9iuEADzggCCxA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cq92796c46d06s43t079xc89exe4vd52rh30c9mcafmne62dxyhqrupl4l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1TlVaSjNvZGtlUE5SRTFV
            amFac3ZOQXN1NDRpNVRTUFRYUGJNbHJFcTBZClFOeVgvSFQvTGJobEptQlNzR2t0
            aWhvVmo2b0UyNmVyNEF2NXVCNHN0c2MKLS0tICtPdTl1SUJvRG1saGlTU0RDa3lQ
            VU5RZjJ2c2VvTjMxOWFpK25GQkc0dncKkvW1H0Nz+cFUF4UIICCbsISjixvL1fw+
            sCptPRj5aoeij8xqCrWYW2sa1tLpVfjgrEwpYcHqfX1gDSSujI/a5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-26T12:45:16Z"
    mac: ENC[AES256_GCM,data:YWbWYLtD/MLpobBUUBhODgmuh9rFbDEQ7WXQL9ZGpSVBpmS8k400B5ndwTpiu8sC1y5oeaNTvFRXACR0WQ3hEU1lrcvuXalAg7cW5CvoIyT3LuUg2/5jN0C6nAe32CjRz2TiqLY38Xwz8t7Z6Q8MXkCL0JA0yBEwZeoEmassX8Y=,iv:+snbP5dUKF3caIKJngsBh+WhL6MPSH1POWakIGr/+Sw=,tag:XbYhjTpI8q2bIxpSRdOHHg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
