stfc-cloud-openstack-cluster:
    openstack-cluster:
        clouds:
            openstack:
                auth:
                    auth_url: ENC[AES256_GCM,data:hLFeOx00iQ+VzSR8ji8hlOsbVv7rnVtIPlX/ocEqLJTN,iv:wt+pyWipqow2MP2hdxMOW12bzN4hchPC629D7vus00Y=,tag:zVCgJkIHuoO0G5YFGWnaBg==,type:str]
                    application_credential_id: ENC[AES256_GCM,data:bDyemD6Jlznf9lEp7WKM69hOKM0H8Cu6zsh4uBgoWHk=,iv:sZd8TgqtTO1XXEPw1VrTkywRwPFbbIRRzcyFF0nCL60=,tag:5cJl2vttQ/B4I9Ta6WfQAg==,type:str]
                    application_credential_secret: ENC[AES256_GCM,data:6lG0/uJBSPT24ZsziwF9wzVOB9iUIWmZ6U1rGz6cRJlplKm0FLqsU3xQqmyxlJTynQN/d1gh9x8nsBhUYlP1z6bovtJfsTi/yqQHfxyLnT9mpEuBNi8=,iv:JcgNlSv6LKxJ10+mQX5A9dAbonM5Oidnv3zSH7/G4yM=,tag:AaBxXgtpxFM1kpJVTgfRVQ==,type:str]
                    project_id: ENC[AES256_GCM,data:gEetk5EHmRTNGtk75V5fjYHq9i69Wvlh1R7OQ1b4P+Q=,iv:xPgwsWo5tI7O6NM4kepDhck+fozY/CzXqHrkTXtcP4U=,tag:co0EG+twTiaA5+EsD6JDWw==,type:str]
                region_name: ENC[AES256_GCM,data:CyZ41L4M/i0y,iv:64c3ixG9CtBzo8TG0MLbGQ1Yv8VIcXt/XJ+i9nizNjw=,tag:jOmSFspGba53s4a+e/hJqg==,type:str]
                interface: ENC[AES256_GCM,data:+bPA73d+,iv:/LDIQZDbGuGsJBPZM9WM3wnZS/pF0yfw7u1HsoNbnQk=,tag:MxxgCl2WqgVBdAuvj6P5HQ==,type:str]
                identity_api_version: ENC[AES256_GCM,data:pQ==,iv:g4Z46KchruefqZ5m/SdhvI8SmL34596nvRQ4oPxtCsQ=,tag:MC6AxJ46CFENd4qyQPsQJQ==,type:int]
                auth_type: ENC[AES256_GCM,data:b+/ijpbdOkzZY1iQFi4ekXulSWLXa3A=,iv:BGKhUiLKqk9n2K2m+Wkpfzzj3YMTR0wSAjNCn7rzhv4=,tag:ZnaZOdi3Q+msUFmfBxscog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cq92796c46d06s43t079xc89exe4vd52rh30c9mcafmne62dxyhqrupl4l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNDJOSk9ObU9uTjJFSVlq
            c1c4N3dUNmhJTWJHMXltSko0aXZSZkdneEc4CjdINHg0RzV4QWpEbEtJcGRvNm9P
            Y2t4SWVBalRjYjRiei9rZlRleExzWGcKLS0tIGlWTStVUGdWeG9wTVo1SUFHWDc1
            Q29CQWhzUDdhOTlaMkVxWEREbDVJVlEKnsN6hAEFgNel1mgvXkqX4QcaA4kkeoEg
            +uC1rdnOYvHLstmqJZWLWEXRTW0D9bBr+QUuev6t7gMbxHUbkYvsew==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1p9q4tzawn9jh3evsgkuslklm2d4zhwhyhtcfls7n62a8cdpv8vqq7t9hqv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZYVFPc0xLM1JQU3ptbmh6
            V2doOUNlNUx0MkkrZksxVHVDZ3Q0WGdlcVRBCk5tYThNMGFhUFk0all6NmxBY0xu
            dlRINFhNWFgvWFlSVU9ibEVRWVYrNjgKLS0tIENCb1Y5UG12cGk3WHU5Wlp6MC84
            VmJpREcyMWVwZ0ZKSys2YWYvbDF2YkkKZeCEKHr1aOfMZ/9HVGJrXq43hzVbK/TG
            eOejCHfvX/X5tDtoa4Yi5tSdSPOPN7gT/nhjmp2cKMol57Q5u/voJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-10T07:45:52Z"
    mac: ENC[AES256_GCM,data:RdSMagIQ4Dyr4uuwXnzHwsOEWj1Obso/E27Ag/Icp/tkdUHRapGvswva8N2z5M/o4kZkFV9AEB5/0itzTlz3my1MHQueRotr7Pr9Kn8X5c7vNES5zu3VWGY2qpZ2I1Zx4PGGP+HLT28ngrmdhxww815Wwa4NwmGiqCUoX6bduDQ=,iv:ZFFgbXxRFpShCPcUl2Ghu3gjDAlaEUUa8a18AUFQzCU=,tag:7D1aOmK5lkSkrxhqpABZaQ==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.0
