stfc-cloud-openstack-cluster:
    openstack-cluster:
        addons:
            monitoring:
                kubePrometheusStack:
                    release:
                        values:
                            grafana:
                                extraObjects:
                                    - apiVersion: v1
                                      kind: Secret
                                      metadata:
                                        name: grafana-iris-iam-creds
                                      spec:
                                        stringData:
                                            client_id: ENC[AES256_GCM,data:QLR5YPinFYbcQAgfz9ZALM7qYJyEO/+A94yt4w9dsTHSv1vY,iv:OHXB9u5KzXxkXC5BDKI7OCfgOwEteFpUI7HHEhx4H6A=,tag:VDtvlwOeSxEZhjQIwwRm/Q==,type:str]
                                            client_secret: ENC[AES256_GCM,data:hWiGknGffBZXkrC5D/p8zwWqsH7ccLSDm2QknN2v6TG2VttrdEegPAI191WMxSejKbk/6LTunZTVKadiSUTvzpzPtHehOQDqDqKKUUBug2a6nIIsQbRL,iv:BQZzjEENdoWK47A+X5Z9gx6GaOlUFwTGKBAyYNExCTc=,tag:Xh2Ijw0px/AAwEl82S4lvw==,type:str]
                            prometheus:
                                extraSecret:
                                    name: ENC[AES256_GCM,data:JGoDFejMDfJusQ==,iv:iOVzdn1Xm0ja8ntRtBeGffOz1Nv9yBW+9GekKJ9rkwI=,tag:akecjYcPLq+1giQhaBQjEg==,type:str]
                                    data:
                                        auth: ENC[AES256_GCM,data:UJ+3svxBeBoahcODPX+FiUdvODhfhGpwTB7i6EPR0ystpzkzqy2w7Y2TSg==,iv:sZa2Nw8WhECceb5zXc7DUOIqeIGm31RfrjxvvMwL4cs=,tag:uFTE8zTzupek7JA0K4G0Uw==,type:str]
sops:
    age:
        - recipient: age1p9q4tzawn9jh3evsgkuslklm2d4zhwhyhtcfls7n62a8cdpv8vqq7t9hqv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NEtRMW8vc0RPZ2FQUlVW
            Q2dUMy9rcTNIWFp2bCtCYVVGLzcyYWRlNVMwCnZYdW9JU0RNanVDaXROOGhmWDM1
            NWdzcXNXNWZRbVJ2ZWhYTTRtMU5VUmcKLS0tIHgrTHIyb0FBdFQ0ZWllUHA1aVFQ
            OC9pRHgrSDFHWDN2Qi9YZ1NZcEdwQ2sKQD7eLpzF8565bvSTUSWJFlEE7YhixWDd
            xppvSxZif5QTYw5dFl9StPwhRNcCQVqxLlcmOwwC/emg5YUAYnJzLQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cq92796c46d06s43t079xc89exe4vd52rh30c9mcafmne62dxyhqrupl4l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZHM0KzNhWm9QaXAwdVdp
            YWdxQldKK3UxcTE4RElacHRLL0hRSVRzUVY0CkpQM3IvZHVSUk5iSDcxVmdHbzR4
            L3VFa21uZXJBWlBaUklmOUpxckx4TU0KLS0tIFJhRmhGV3VFZHdSWGtrdDNYcFcy
            Y21DRTVHcGkvTzNyblFNb0ttN1BQaVkKO9odhmRrDt0YeiLxTUe/aya96rBtNqA1
            bGKpzGpdF/9jnvAhphoIVjqOzkxM75Ai0j22fAy8drR6GuX2ky4MwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-30T15:57:13Z"
    mac: ENC[AES256_GCM,data:+SfmD0I4nvysjTcJXBx3Ihqj/sq5uRZshRNOohR7NzA0aEfmUjPTHVtrnDDhaBwPH8WRuPsV4koCqh7wLCuZ/ylpVFR2KZ475pilExCCF0A780avD5DTlXDRsqc1oLqkpN2OoNAkDTK2iYO/Qq5p26LIl8ZJHUDJpIXFvqsb/XQ=,iv:zkUritTmFtQZ0BK/qVW1Z4fPk42+/6Q9IQ2qwFVGiJs=,tag:e+aFDe9FdsM5DC9lVVfExQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
