stfc-cloud-openstack-cluster:
    openstack-cluster:
        addons:
            monitoring:
                kubePrometheusStack:
                    release:
                        values:
                            grafana:
                                adminPassword: ENC[AES256_GCM,data:z4vC9O6yJB1eus3vnd6JHpZc584=,iv:gnF2ToDSsS4rvxylBw2Xj7hUJQXqjyMpc9jP8rRuN7s=,tag:tJx9DN5/K8XkdmYIre8REg==,type:str]
                                extraObjects:
                                    - apiVersion: v1
                                      kind: Secret
                                      metadata:
                                        name: grafana-iris-iam-creds
                                      stringData:
                                        client_id: ENC[AES256_GCM,data:wx2ztrVo0rHtgRJzz7FfCVlHSBjAtasmCxrQsXh3J2Ibrg+z,iv:JAQZiWo++GQngmJf6h9Mn5ocME7ca1EMjDgTc1qRRRc=,tag:EUH8nqk1zTDLD0J0AYCSsA==,type:str]
                                        client_secret: ENC[AES256_GCM,data:JdZo+rEekKY2MbC1yd4jTBQi6cN7VSLbdv8ngUYOpqBxXyWOuRyG+JmyhUqwUQ7CMdpmkVL8UBLM2BmHBUmYykBjPGtgXJx9Lr/UiqqqcBZRZQReQMZa,iv:9m7QwAdQD9RkxlInDlAlj+qeUVJIVe1ZDzyFVRkud74=,tag:Kmmo03wn1gVbHN4BBqgKZQ==,type:str]
                            prometheus:
                                extraSecret:
                                    name: ENC[AES256_GCM,data:JGoDFejMDfJusQ==,iv:iOVzdn1Xm0ja8ntRtBeGffOz1Nv9yBW+9GekKJ9rkwI=,tag:akecjYcPLq+1giQhaBQjEg==,type:str]
                                    data:
                                        auth: ENC[AES256_GCM,data:UJ+3svxBeBoahcODPX+FiUdvODhfhGpwTB7i6EPR0ystpzkzqy2w7Y2TSg==,iv:sZa2Nw8WhECceb5zXc7DUOIqeIGm31RfrjxvvMwL4cs=,tag:uFTE8zTzupek7JA0K4G0Uw==,type:str]
sops:
    age:
        - recipient: age1p9q4tzawn9jh3evsgkuslklm2d4zhwhyhtcfls7n62a8cdpv8vqq7t9hqv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NEtRMW8vc0RPZ2FQUlVW
            Q2dUMy9rcTNIWFp2bCtCYVVGLzcyYWRlNVMwCnZYdW9JU0RNanVDaXROOGhmWDM1
            NWdzcXNXNWZRbVJ2ZWhYTTRtMU5VUmcKLS0tIHgrTHIyb0FBdFQ0ZWllUHA1aVFQ
            OC9pRHgrSDFHWDN2Qi9YZ1NZcEdwQ2sKQD7eLpzF8565bvSTUSWJFlEE7YhixWDd
            xppvSxZif5QTYw5dFl9StPwhRNcCQVqxLlcmOwwC/emg5YUAYnJzLQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cq92796c46d06s43t079xc89exe4vd52rh30c9mcafmne62dxyhqrupl4l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZHM0KzNhWm9QaXAwdVdp
            YWdxQldKK3UxcTE4RElacHRLL0hRSVRzUVY0CkpQM3IvZHVSUk5iSDcxVmdHbzR4
            L3VFa21uZXJBWlBaUklmOUpxckx4TU0KLS0tIFJhRmhGV3VFZHdSWGtrdDNYcFcy
            Y21DRTVHcGkvTzNyblFNb0ttN1BQaVkKO9odhmRrDt0YeiLxTUe/aya96rBtNqA1
            bGKpzGpdF/9jnvAhphoIVjqOzkxM75Ai0j22fAy8drR6GuX2ky4MwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T14:50:01Z"
    mac: ENC[AES256_GCM,data:70IsD1EzSfvttCFkaqSc2L7WVxDXudDO2A1vqmmvlWYmdkx0U5IYoZC8okDTNmmotfmyudszuR1M/Nu7dyTeMXXBl4Jd+v+hDCMX1RoZ5DrueyeS94nA5tmZ9J7mI6zPdHTTbUx2O4Hv8Wkt9oGpIwQq7kxHQTFkHWzJmeX7qyc=,iv:hGDTrkkqUy9TEc5aln/5SORhnA4t37j6tEpIhi77oTs=,tag:ojsoU3ZjjobIaFaVTCbWzw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
