stfc-cloud-openstack-cluster:
    clouds:
        openstack:
            auth:
                auth_url: ENC[AES256_GCM,data:/EEm1EVeEvr+x2PEom0kVXb9PDIPIiB/RkYg0mfwBghZfBPBaw==,iv:tTVK1gg9f8aNypDloRXiQpIEWR6nQds7luh9vwNcRnQ=,tag:yn410QAnkbycS86vEfDyYw==,type:str]
                application_credential_id: ENC[AES256_GCM,data:bAzUTnlM943ztwJ4DwbGiP/1z5FoIAj5mWjpmtF3haM=,iv:VtXlAjWunImfMmm9R91ypL8PeLDp01cJxT2mNCLwgqM=,tag:NkWmhO1DoUULKIjlTjS43A==,type:str]
                application_credential_secret: ENC[AES256_GCM,data:72pqsyR7n1qURCRsxpybpuYosNsdGlLsoCorwhaw9fkQ+Jz7BvXwGsPVLeWjPy/ja0s2Hsj1+fO+6G0oSAFURlSdjiI64ryjBxePjEZCLArmBVBhyDA=,iv:LDkuRfJ0sILfKnuCHD8doMZhrU/oTi0sLLrtfRbUfw4=,tag:oW7efelq36DikPaXXQ1FoA==,type:str]
                project_id: ENC[AES256_GCM,data:5RJb99g4SJtDg6KaF9OaJDVWkTSy9A3yjaMm1eT8aW4=,iv:vQfRRdb9pZst0WuFmAFn6kmrSO5w5lw3sFyg3p8fEmE=,tag:OCGFqFpmKclPGYOt2IDASA==,type:str]
            region_name: ENC[AES256_GCM,data:R8twLNq75Qh4,iv:dMCT7bvTUoxtAdNaeP9ekzVZeggMfgivWzamoLl/AYQ=,tag:TLYJfhe3Ip7BGgy0zNG2Bg==,type:str]
            interface: ENC[AES256_GCM,data:qo/93d3E,iv:kkNra9cOa7DMNEnQMmVptdfeJLXZ5RzGLkPLBFw/fCE=,tag:GlDSCkpi1w1inm2NOJJinQ==,type:str]
            identity_api_version: ENC[AES256_GCM,data:Ow==,iv:45ZotqIFNULa9TL8c4rN6ZkrWUjDb3rAB54F5BK6/PM=,tag:dCVBgpeHHrOLA/cM5gDGzg==,type:int]
            auth_type: ENC[AES256_GCM,data:hKb27/X1WIG8ZTuQFKvEjgq7BAEY9K8=,iv:OzEaXfA/R3IrSgYBYXKxZku5XtDwU/QXW8Aa2j9OADg=,tag:uXxQgLcUV+dXOz149y4EEw==,type:str]
sops:
    age:
        - recipient: age1tgfg98jddwc2crr869aa9phe9ufflnyya4t3mcltqsmcvca0k46q2m04se
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPKys2TjRrSlFXRS9aN2tq
            L29tSjJKREJabExIL3hlcTdodURCZXk3ZlZvCjAwQTFjZnFDWm5NTjVTZ1Y0cWlk
            ZUNycjZJNGk2dk5Vc25rY2s0cGJGZXcKLS0tIHpydEV6VGlzVU1pY2JJSXRrT2t0
            MGduaU8wOE1LUkozZnQwQ0ZOcnNTclEKmfXvmbsLvQvJ3KMFzsPfBQEwlOPL4E0N
            WhXENaG2fV648StPUZs5ecYayWTPDSOeDijOhu1OCg0/sd8milBQyg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hsll27prywydttq7dtnqtdnu2jpr8zhaulx00l7n4pqmxkhr55vspqmj6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTk1tblRFYmxUY0FMeTR4
            dEhmajJESk11dVhkWDBhZUI0ejJXRS9VM0hNCmw5ZFlzMlVhdHMyU0RPL2t0ZlBN
            ejFVSFdOK0RMVEl5a0s4TmNPUmYvZVEKLS0tIDFWRXNxUWJPNWMwdFl5KytOcy9l
            RWt5cFBwaE1YSUZlSE9JbURyNWxlbEUKL64AvQiY97/6EVoY+8RRYJLOUZ9dV9i0
            dRQ6cPM3suav8Wyug50eKGMVwiX1VhaINh9t3Tnhb7QSqG0oK9G6pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-02T22:58:33Z"
    mac: ENC[AES256_GCM,data:C5vxNb/2CtRUJvETTLmLSii7XBaYgyEQ0YwAZqEijx280YBYd19ioEn+HuCvEzXs8v5D3C3upbKyf6r27f3PCTmphDI78vO5PaphkuS88HBkzYf4jwVzxwU4aPBfghxOIZNrByEXqZzJ6B7lgsxCfJKN5HMiFylSm3Y1kTuEeaE=,iv:rxpk9cxTj2/leM8X3byR3V0GRREQ6mwpuwUFwks8aP0=,tag:RttVuYvuAGrEC7E3pMq/Jg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
