stfc-cloud-openstack-cluster:
    openstack-cluster:
        addons:
            monitoring:
                kubePrometheusStack:
                    release:
                        values:
                            grafana:
                                adminPassword: ENC[AES256_GCM,data:KZpad7BupHlTcc4pJ360Jn8SOjM=,iv:6jbSCiNPm2TDtyJVRNDvhyeqTZ8Hn9CkBdKUHuB43H8=,tag:ezNU8Mxt6a4utVmGnxi0xQ==,type:str]
                                extraObjects:
                                    - apiVersion: v1
                                      kind: Secret
                                      metadata:
                                        name: grafana-iris-iam-creds
                                      stringData:
                                        client_id: ENC[AES256_GCM,data:yfrafCiGvwp0Dau+uYOsUefY5Yz6M8fdXDr8JZPym8SAsJj4,iv:mADTLMUYTz2p2/UyGoNRU6nNsINlO2J+bHfB95Inbxg=,tag:E0PWGpDH5D9sq4eP6dJPLw==,type:str]
                                        client_secret: ENC[AES256_GCM,data:mYbsU051QaUeyFlHpTxBwCgJ8ZPo4//RBB2bSHYbpp1A420yq3JX4o/rWBj7BDpsqEiQkXIv3rNInpM737XgEr3QRaEOXpTiKLv1SA9Pnu88vjJcEGg=,iv:83Ne9ttPMhRHF25QZRIl7sXVESRo9ULhjydAZ4MlZhs=,tag:Nm7S6x0De/gsihCnYwfrkg==,type:str]
sops:
    age:
        - recipient: age1tgfg98jddwc2crr869aa9phe9ufflnyya4t3mcltqsmcvca0k46q2m04se
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZW16YXpWTlJTSVZrbnpO
            TGdzZDlLQ3Z0by9TU0JINitSZWp5UHVmeWowCmZwTWJYdnNvaEFaWkIwcXgzR01B
            UHUzbzMvZkgvMC9BejZWa0NiTW9oeGcKLS0tIFhKQ09KZmJwLzQ2ZW1yMlRXTWUy
            M1hOMnN2N2VuTmdJcm01TjdtcDZwbzAKRvCYe/0qbSmXc0CumMNfqZY47CbtgEVd
            dazHAx3LgVYiuY2ToLoQnBE55SeZyF5VmYfnCIqYGQb3QudkFwTWLg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hsll27prywydttq7dtnqtdnu2jpr8zhaulx00l7n4pqmxkhr55vspqmj6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqblY3M2RaWnYzSmwxTzIr
            NzJUUGFzcDY5enZEMEtUSkZ0U05HWUhkUHdvCnZ2R2w3TCtYVXpHbzRsOXFuam5Y
            Y2VlUGxxR2VjQVFLQmZ6WndsT1QxV1UKLS0tIDl0YmJrZmpCR2pYNUpRUmtJQURn
            RDhjWnZvc1NFRGJ3eEFxWVR6UjBtbUEKRYMv6EgV9q+aC4a1RGlvO7flAWf8idx/
            vp1K6QR7HgIFQ1YvMhA8XRW8TRTSTV0nw+hLJJw/0Ej3xJ+RTchCbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T10:02:13Z"
    mac: ENC[AES256_GCM,data:q+Ik8TDnOHK4n9ES20KX2KreWuN3FQRIpyFhDETfV1ZQ/McI+GacDmd2m9joapoP8D42ajkl63yrh/lUzLw0wcL8zBjSOCQ3rbf135ni2BuFc2DYiekrk21fArW6/o9whLOCQPBARI7a9uSZ3vFBLGHT53o3g2tC5wOkyqdeYp8=,iv:jqjzL3ENREYJdYG6rN6DYHsUxCUth9FrGs/AGdkydnk=,tag:5gOw2+hwLz3WuCf7vSHdnQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
