stfc-cloud-openstack-cluster:
    openstack-cluster:
        addons:
            monitoring:
                kubePrometheusStack:
                    release:
                        values:
                            grafana:
                                extraObjects:
                                    - apiVersion: v1
                                      kind: Secret
                                      metadata:
                                        name: grafana-iris-iam-creds
                                      spec:
                                        stringData:
                                            client_id: ENC[AES256_GCM,data:K06jorHny/UctjdAjI+bAIpdayNtopeIVD6+dw6n3w+JNV2F,iv:iTLTp6NvdllIR3L7GCJZxca15lO9r7DRT6pKN5+0X/c=,tag:zFpd0EFvXdht0FFLul4reQ==,type:str]
                                            client_secret: ENC[AES256_GCM,data:/3Lvkfh1E2fVJ2xhM+vOnHoghPGP8rq/2IQPvdxGKF2e7C+Sxst5zrGBJkMzAWV1fwQop/WwWc8VmUpdDokuDaGu3I0Yq0EydHwfjXV8h2F13UElEvs=,iv:+RkQXR3GDnn7Sq084+hJJVxhNDWabhW0J4LFPEeeyZM=,tag:bDtBYdm8yh8BjIO/LsPFGg==,type:str]
                            prometheus:
                                extraSecret:
                                    name: ENC[AES256_GCM,data:rbIjxW2qZryPeA==,iv:/4CCEZpVpaqKIZL6zMlu8zIrH21zoyuGrpyaiI01Vkg=,tag:5AZdZQ3iUmZbQ1+sJEwrpQ==,type:str]
                                    data:
                                        auth: ENC[AES256_GCM,data:gIkmHzaZAxuRQZhto9kdpuqvtMg8KJvofFXTb8CmPCEtnNmANI29TbhrzA==,iv:dVu5OungIBeGgK57swWUnNznl0xBUbxfbdgAfDvLVRM=,tag:x3eHgFTmBivGq3UIEoGQXw==,type:str]
sops:
    age:
        - recipient: age1tgfg98jddwc2crr869aa9phe9ufflnyya4t3mcltqsmcvca0k46q2m04se
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZW16YXpWTlJTSVZrbnpO
            TGdzZDlLQ3Z0by9TU0JINitSZWp5UHVmeWowCmZwTWJYdnNvaEFaWkIwcXgzR01B
            UHUzbzMvZkgvMC9BejZWa0NiTW9oeGcKLS0tIFhKQ09KZmJwLzQ2ZW1yMlRXTWUy
            M1hOMnN2N2VuTmdJcm01TjdtcDZwbzAKRvCYe/0qbSmXc0CumMNfqZY47CbtgEVd
            dazHAx3LgVYiuY2ToLoQnBE55SeZyF5VmYfnCIqYGQb3QudkFwTWLg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hsll27prywydttq7dtnqtdnu2jpr8zhaulx00l7n4pqmxkhr55vspqmj6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqblY3M2RaWnYzSmwxTzIr
            NzJUUGFzcDY5enZEMEtUSkZ0U05HWUhkUHdvCnZ2R2w3TCtYVXpHbzRsOXFuam5Y
            Y2VlUGxxR2VjQVFLQmZ6WndsT1QxV1UKLS0tIDl0YmJrZmpCR2pYNUpRUmtJQURn
            RDhjWnZvc1NFRGJ3eEFxWVR6UjBtbUEKRYMv6EgV9q+aC4a1RGlvO7flAWf8idx/
            vp1K6QR7HgIFQ1YvMhA8XRW8TRTSTV0nw+hLJJw/0Ej3xJ+RTchCbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-30T16:00:25Z"
    mac: ENC[AES256_GCM,data:z1iPHhCNwKTQrOokI2JsWpsn1+ZM26fUx7tf16KQb/0X9LiKWzS52A3qrovtROi9U9BXdrhNpNNvro/ZvedpWZBD48aE25PT6eFXlGFb/q4MhDQ9/v3CfmGV6ov5Q39//6RnNUAkPq81Jpl5Olxsb7ai0r3Dy9Kca5prOBu+Yy0=,iv:FvZwrPUTd9DMK3F2+rMFrhnRzJEfDNd/cWnKO4j94e8=,tag:ZIx5MbPoSf9wY5nOsIENFw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
