apiVersion: v2
name: harbor
version: 1.1.3
dependencies:
  - name: stfc-cloud-harbor
    version: 1.1.3
    repository: https://stfc.github.io/cloud-helm-charts
  - name: ingress-nginx
    version: "4.12.3"
    repository: "https://kubernetes.github.io/ingress-nginx"
    alias: ingress-nginx-harbor
