stfc-cloud-openstack-cluster:
    clouds:
        openstack:
            auth:
                auth_url: ENC[AES256_GCM,data:+NFTd6D0xVNYlDRLT2ZTuNvrJ7V7IR6jQRIWy/IMfiok,iv:2zGAXWbU+SyE2KytaepfSFkQbU4/KMXjObTDQp0mvl8=,tag:aMaMlV7orZgov3+9fmZ8qg==,type:str]
                application_credential_id: ENC[AES256_GCM,data:wmPMkJik59BfcstdjEE8SRjWKeQDzWelQOyUb5nx+4o=,iv:hpYI76zw0foxuq3HN9apF/a6rh0ksKEw9ml7w/Xcdxk=,tag:N4FfoM0DInV10BqxW5VVkw==,type:str]
                application_credential_secret: ENC[AES256_GCM,data:sHl6VJpXh9XpQFWzdMq/xnVmTrlVu0UgPBCIvIlAOd2rZaRAI4GFMU1YvV59ymFOxjwFzHjxq5Fov+17kleYtPee96z/4gMMSSRo18NP/yKxg7PCP8Y=,iv:SKtx9MLa/9Weoodk4/LRvztaJquuQbDN2ty++69T5ng=,tag:Zd6qsVkWGUkwHwXLImDliQ==,type:str]
                project_id: ENC[AES256_GCM,data:xBCg3r4bTiN/ncYPE2QTu2JdjFR52ro2kcB6aCVOCFI=,iv:GbHCfBJyazfZq7Rj+6pJChmddkHmRAwBabvftjtpEWY=,tag:mlxvMscQsgZnvRKeGpGajw==,type:str]
            region_name: ENC[AES256_GCM,data:4rglos7h9LUc,iv:le5nAgFwWK+WcMAL4Bzgfl/OcThZKf2WNMmL/2REUpg=,tag:ZqtHq4LhGBtcVHuB5GRQjg==,type:str]
            interface: ENC[AES256_GCM,data:r2MYwS5r,iv:rxSvFB2pm7uNZma13LS0EmmHgLhLeW+hN3xogr2tx88=,tag:ladabW38UU5s8OzvI1HsUQ==,type:str]
            identity_api_version: ENC[AES256_GCM,data:KQ==,iv:fzh6pOn29SzNyDMivapbfwxsglWh4cGmkW3N2gApIK0=,tag:bD+TG2X1w4eBSqbN1k2eFw==,type:int]
            auth_type: ENC[AES256_GCM,data:K4A+WhAXjXBGru08r+1NzdRhzR89FR0=,iv:YH9avEdmQI2ME74hrZo+jr+f7dopwGJxdcPY9uJBrB4=,tag:UYaqwwSbM2xlUYLFQPdPbw==,type:str]
sops:
    age:
        - recipient: age1tgfg98jddwc2crr869aa9phe9ufflnyya4t3mcltqsmcvca0k46q2m04se
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTXEwbzFJQ1pmOGMrUmJn
            MjdIdHJNWnAxZm9wY0MrV0l6QUpycG5TSURFClR3WUtTZ3AyQkdWVVRPb2xwTlVF
            M2VTV2tHandrRFk0U3dZWGFXUmNsTlEKLS0tIGNMbDdJTkxua1hscVZlZDJIZE5m
            bHRxSlpwVjRWSExoMldJR0Q5Z3RxL00K/jFTieKuOmsCAVbFsS0FcDf4dKzshNWL
            sYxn1O29ExaZYXuN3i4ksZ4GUyIXK7pbjaOk9SOvM/mN4gFwnHHYVw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hsll27prywydttq7dtnqtdnu2jpr8zhaulx00l7n4pqmxkhr55vspqmj6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUGFMSkRMTTkxdnJBS0RX
            K0xISUdMd2drRWhVVFVJZ2ZqT241TjdKQjJjCk40SFl4MkRxN3Q5MUFyV2hJNytN
            UlNMdnVKenFmZjFZcWJwS3R4U1JZdXcKLS0tIER5YUw0b3BCNU5jWlBoZ0NOd2xi
            NFRHQTZwcEs1ZkcvU0ZYRVRsVzJaSk0KZmiSLj80QBnrEFNkHSgJXteg8DLMORn9
            uhKzx6kk0Vg6E44J225T2EpxRvkDIH49nv/RrFR0HJjmE9slOu6awA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T14:46:13Z"
    mac: ENC[AES256_GCM,data:QNGAnzZ2Rwj0iA6sEmYikcozyIFrPjC9JfPDbKr9JOo1mwvy/K/12caw0ljLVBcQJs173zt6K5nXJGVXfiuttskiygkeLw3quLiLX97W9SooX071rpMTuYSfm9gSLuIVAF1LHu4M1I0aLxOIbDrgK1j9GlFEPDs5MROisPpGA8o=,iv:T2NDSkLpd+KSwGIuiq+PtnKL58g5iCV8T5zSVJD3aB0=,tag:AEe0TB2nG3HzyY6lye3OkQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
