stfc-cloud-openstack-cluster:
    openstack-cluster:
        apiServer:
            floatingIP: ENC[AES256_GCM,data:szB9FPgXzi4hNrMuMg==,iv:ac3zU+vmoKAOg5gT37gPOX7rlZKJYgoJw02GyW/sZkw=,tag:4/vEanPPsx0sTpMnz1ZKXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cq92796c46d06s43t079xc89exe4vd52rh30c9mcafmne62dxyhqrupl4l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RnZMb3lKZC9yL0krUW5m
            MkxVbGUwODlNclhlYlExL3ZMaWpqbk5STmk4Cnc1aWNwdVg3OXVUR3ZxM2UrMkE2
            VDZEZE1tU3JycmQ1cC9qRU5vU01KVGsKLS0tIDIwKzZ0QVFDSHNib1R2OGwrcU9X
            MTJjSVU4U1FITjVGUk5uR3lRZGNPZVEKQkYYDRi3OjFJ9cHYbO1mbU4gnGZ1U4+R
            cihSWyBikgMJeyTTrbDLWYwqxnsfWQTB2IwQymH/myLtr1nrds5KVw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1p9q4tzawn9jh3evsgkuslklm2d4zhwhyhtcfls7n62a8cdpv8vqq7t9hqv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYdG8rM1l1cFpYTkJJZ0wr
            ME52aTV3b0RBc2Vucmo5WFBLTVZHTFBhZXpVClBJRHV6QVBUb2hBQ2JPaUcyaVVG
            SE9NeEp1MFFwbHM2UkdWTVFiVUgrYUUKLS0tIGFSRXc1TmN0WkFtRlExRVRScmVF
            dXUxS1lRTWRVOXQ1M0ZrZi9rSUVSeGMK06s5QsNfzYDmcEUS9lCY0DTqylZWLNyP
            XgSVYS4BPJ2mCxmDHKQHE7kMbEpdj1C6MHWeHU5d73cK10zwTpGm0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-10T07:42:44Z"
    mac: ENC[AES256_GCM,data:h3ozxaTDQ3jj4hzEu9dVO2cGw134ZLp41DHt3UQljHJL0uQpibhxUJ4bfmp0zp74vXu61XdlY/W1K7+/LK0SvsmY3X+OokwgqUzZvHzjFkHm3HewQfDlrIY5+wOxzetBOGkZQxKG8oarc90Yhiwz4TX5tkY9n4Zmgu5EGKKlN8U=,iv:Ji6fSiRkgiX9nI/7UtZ64KIcBAp2pepKPg1G2cMvfWI=,tag:s42qbW8nUPIyQBll/aIX7w==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.0
