stfc-cloud-openstack-cluster:
    openstack-cluster:
        addons:
            monitoring:
                kubePrometheusStack:
                    release:
                        values:
                            grafana:
                                adminPassword: ENC[AES256_GCM,data:BLgP9feQ7qONWH1U9crq5kcmZcc=,iv:dWkw0keOR5Mdk206Kb4Dt06wIoO53YnnNWFus/ZAGqQ=,tag:rK/4zZgaxnYmuVxtG1/MXQ==,type:str]
                                extraObjects:
                                    - apiVersion: v1
                                      kind: Secret
                                      metadata:
                                        name: grafana-iam-secret
                                      spec:
                                        stringData:
                                            client_id: ENC[AES256_GCM,data:QVHlWHQ6trYgMzfZ24odFEZC5Tgt571SczELMWmQbMvTtL7X,iv:RlOLt60acEQeI2A20HmF8GyQhRNpPy7arKygqPn4fEQ=,tag:juN7RBur+92+yr3XRKHNkw==,type:str]
                                            client_secret: ENC[AES256_GCM,data:3YWiSHy2SxA7qmX3chHhGa//2BoAWCOVwoOfPS2dgtICvjR+MlvNogFuW1bK2OMZiUUg/YNxJ/h4X7+GPvp0NE5X43z206Vp8lAmlho+Ina9IN7vhLU=,iv:+b5SNnlvHrwpVpz2jk3xUtSX+fQBtHEOvPcbgVbHBVg=,tag:SX9+0Kqx7qwB4gxgPTIKXg==,type:str]
                            prometheus:
                                extraSecret:
                                    name: ENC[AES256_GCM,data:kG0viOOJLrYh4A==,iv:uIdxCcxMEZlAAKtOUN8ebCJO9ceCvMmsNU21Z5UPbsY=,tag:CzEg2TdwYFe2A7A1mH23tQ==,type:str]
                                    data:
                                        auth: ENC[AES256_GCM,data:beYEQV49S6ah4gHcz4mU/x0jb+HcYwzOIhjLH48g/wlo2eJIjoPs2y7ozQ==,iv:lrGm8EhzRscK3n+0KLQ0im90FG68aG+jZThbGweeZMM=,tag:65yyAlLKbR19ite+tqz23Q==,type:str]
sops:
    age:
        - recipient: age1p9q4tzawn9jh3evsgkuslklm2d4zhwhyhtcfls7n62a8cdpv8vqq7t9hqv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjQnVvQTdGb2F6YmhIMSsz
            aFg2NW01R3lZek9ETWlWTEFKakJCTmcvc2pZCkNIcldFR0NLc1dzYXlMdDd2UnNV
            VzB2K2I2amJaSllSRWlJSng3bnZEZlkKLS0tIE84djR2VjJTQXJqTGwzaGppalpL
            SnYrY1NqZkJLeDdLVkNpSjhQQ2J3encKoTnA5RZyZgJ5R6NhilW0I/f13iuZb0nD
            p4jbkZgmFkj8IR39+SXFeg5jmBkV9HmGJTYhxqlC7yE1Bf97GBwoug==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cq92796c46d06s43t079xc89exe4vd52rh30c9mcafmne62dxyhqrupl4l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZitBb2JtSnM3bTBLRWxC
            MTR0UTd3UXVyZVMwSVB1VUowcmNIYTF3eFRFCjQvdG5WcGpKZzFYNmN2aVhmcUs3
            a0FHcHhhdkJIR1hGZ0VHR1JWWTNNM0EKLS0tIFh3ZDRXbjBkU2t0aFhwWWxVNWpt
            T0l6QVJNRjNEM1dYTWtCWDR2dElDY28KiWHSh4M4VQFyxueRxJh5/b9aYbvVqcZC
            jVPpydA19tMIwFEoSOifSUnte2jghca+DQLdUYfWa8x896TnQscXRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-30T16:07:07Z"
    mac: ENC[AES256_GCM,data:hUOE3baYvL1xxXXV+vm2B5omOGfnS7q1NTqLE1iRJLZ8VZR+rx96LstcpQrCSvTj30EjEvlZwe5vLgNWgNg3qTTlRozxehQIASVCYEYj3izKzMe7wH+zKfFPJiYNSSKQicBlf0yzH0EQwk7Ixw+mx8kP1OBP1GuHsveWrvhcG84=,iv:5l7S8DJgdOf7XMBZ9UX43MYsEUeVk0es76UxYOYQRXk=,tag:ul/t8hNLbvgPqsIa25U77g==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
