stfc-cloud-docker-registry:
  httproute:
    hostnames:
      - dockerhub.stfc.ac.uk
    parentRefs:
      - name: envoy-gateway-external
        namespace: envoy-gateway-system
        sectionName: dockerhub-https
        group: gateway.networking.k8s.io
        kind: Gateway

  s3:
    bucket: prod-registry
    regionEndpoint: s3.echo.stfc.ac.uk
    skipverify: true
