stfc-cloud-harbor:
  harbor:
    externalURL: "https://harbor.stfc.ac.uk"

    expose:
      route:
        enabled: true
        parentRefs:
          - name: envoy-gateway-external
            namespace: envoy-gateway-system
            sectionName: harbor-https
            group: gateway.networking.k8s.io
            kind: Gateway
        hosts:
          - "harbor.stfc.ac.uk"

    database:
      type: external
      external:
        host: "dbspgha01.fds.rl.ac.uk"
        coreDatabase: "cloud_harbor_registry_prod"

    persistence:
      imageChartStorage:
        s3:
          bucket: prod-harbor-bucket
          regionendpoint: s3.echo.stfc.ac.uk

    trivy:
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 2
          memory: 2Gi
      timeout: 10m0s

  backup:
    enabled: true
    sourceBucket: "s3://prod-harbor-bucket"
    destination:
      daily: "s3://prod-harbor-backup/daily"
      weekly: "s3://prod-harbor-backup/weekly"
      monthly: "s3://prod-harbor-backup/monthly"
    endpoint: "https://s3.echo.stfc.ac.uk"
