apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-deployed-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/stfc/cloud-deployed-apps.git
    targetRevision: cloud-helm-charts-test-branch
    path: clusters/dev/management
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: management-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=invalid"]
  generators:
    - list:
        elements:
          - name: "argocd"
            chartName: argocd

            # NOTE: each chart needs a valuesFile for this to work
            # so create one for each chart - even if its empty

            # argocd and all dependencies use the same file "argocd-setup-values.yaml"
            valuesFile: ../../../clusters/dev/management/argocd-setup-values.yaml
            namespace: argocd

          - name: "cert-manager"
            chartName: cert-manager
            namespace: cert-manager
            valuesFile: ../../../clusters/dev/management/argocd-setup-values.yaml

          - name: cluster-api-addon-provider
            chartName: cluster-api-addon-provider
            namespace: clusters
            valuesFile: ../../../clusters/dev/management/argocd-setup-values.yaml

  syncPolicy:
    # Don't remove everything if we remove the appset
    preserveResourcesOnDeletion: true

  template:
    metadata:
      name: "{{.name}}"
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: "https://github.com/stfc/cloud-deployed-apps.git"
        targetRevision: cloud-helm-charts-test-branch
        path: "charts/dev/{{.chartName}}"
        helm:
          valueFiles:
            - '{{.sharedValuesFile | default "../../../clusters/_shared/dummy.yaml"}}'
            - '{{.sharedSecretsFile | default "../../../clusters/_shared/dummy.yaml"}}'
            - '{{.valuesFile | default "../../../clusters/_shared/dummy.yaml"}}'
            - secrets://{{ .secretsFile | default "../../../clusters/_shared/dummy.yaml"}}

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.namespace}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: management-clusters
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: "https://github.com/stfc/cloud-deployed-apps.git"
        revision: cloud-helm-charts-test-branch
        files:
          # grab all infra values for all clusters in environment
          - path: "clusters/dev/*/infra-values.yaml"
  syncPolicy:
    preserveResourcesOnDeletion: true

  template:
    metadata:
      name: "dev-{{path.basename}}-cluster"
      # All applications need to go into the ArgoCD namespace
      namespace: argocd
    spec:
      project: default
      destination:
        namespace: clusters
        server: https://kubernetes.default.svc
      source:
        repoURL: https://github.com/stfc/cloud-deployed-apps.git
        targetRevision: cloud-helm-charts-test-branch
        path: charts/dev/capi-infra
        helm:
          valueFiles:
            # Bring in infra values specific to this cluster 
            - "../../../{{path}}/{{path.filename}}"
            # Bring in shared environment values
            - "../../../clusters/{{path[1]}}/_shared/monitoring.yaml"
            - "../../../clusters/{{path[1]}}/_shared/alerting.yaml"
            # Bring in infra secrets specific to this cluster
            - "secrets://../../../clusters/{{path[1]}}/{{path[2]}}/secrets/infra/api-server-fip.yaml"
            - "secrets://../../../clusters/{{path[1]}}/{{path[2]}}/secrets/infra/app-creds.yaml"
            - "secrets://../../../clusters/{{path[1]}}/_shared/secrets/infra/smtp-smarthost.yaml"

      syncPolicy:
        automated:
          # Remove anything that isn't in the helm chart output
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
