apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor-{{ $.Values.global.env }}
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: harbor
    server: {{ $.Values.global.spec.destination.server }}
  sources:
  - repoURL: 'https://github.com/goharbor/harbor-helm.git'
    path: .
    targetRevision: 1.13.0
    helm:
      valueFiles:
      - $values/{{ $.Values.global.env }}-values/harbor-values.yaml
  - repoURL: 'https://github.com/stfc/cloud-deployed-apps.git'
    targetRevision: {{ $.Values.global.spec.source.targetRevision }}
    ref: values
  project: {{ $.Values.global.spec.project }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true      