victoria-metrics-cluster:
  vmselect:
    replicaCount: 5

    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/cluster-issuer: "self-signed"
      hosts:
        - name: select.vm.example.com
          path: /
          port: http
      tls:
        - secretName: vm-ingress-tls
          hosts:
            - select.vm.example.com


  vminsert:
    replicaCount: 5

    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/cluster-issuer: "self-signed"
      hosts:
        - name: insert.vm.example.com
          path: /
          port: http
      tls:
        - secretName: vm-ingress-tls
          hosts:
            - insert.vm.example.com              

  vmstorage:
    retentionPeriod: 1 # month
    replicaCount: 5
    fullnameOveride: "vmstorage"

    persistentVolume:
      enabled: true
      existingClaim: ""

      size: 10Gi
      storageClass: "csi-manila-cephfs"
    
    extraContainers:
      - name: vmbackup
        image: victoriametrics/vmbackup:v1.96.0
        command:
          - "/bin/sh"
          - "-c"
          - |
            echo "vmbackup sidecar running. Use this container for backups."; \
            while true; do sleep 3600; done
        volumeMounts:
          - name: vmstorage-volume # Matches the StatefulSet volume claim name
            mountPath: /storage

    env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          key: access_key
          name: vmbackup-credentials
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          key: secret_key
          name: vmbackup-credentials
  
    podSpec:
      volumes: [] 
