nameOverride: envoy-gateway

external:
  enabled: true
  clusterIssuerName: selfsigned
  service:
    annotations:
      # prevents errors when deleting clusters, leave as true
      loadbalancer.openstack.org/keep-floatingip: "true"
      # Set loadbalancing method: ROUND_ROBIN, LEAST_CONNECTIONS, SOURCE_IP, SOURCE_IP_PORT
      loadbalancer.openstack.org/lb-method: ROUND_ROBIN
      # Client inactivity timeout in milliseconds
      loadbalancer.openstack.org/timeout-client-data: "60000"
      # Set true to enable X-Forwarded-For Headers for HTTP
      loadbalancer.openstack.org/x-forwarded-for: "false"
    loadbalancerIP: null

  deployment:
    replicas: 3
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  listeners:
    # define separate listeners here for all externally accessible services (by hostname)

internal:
  clusterIssuerName: selfsigned
  service:
    annotations:
      # prevents errors when deleting clusters, leave as true
      loadbalancer.openstack.org/keep-floatingip: "true"
      # Set loadbalancing method: ROUND_ROBIN, LEAST_CONNECTIONS, SOURCE_IP, SOURCE_IP_PORT
      loadbalancer.openstack.org/lb-method: ROUND_ROBIN
      # Client inactivity timeout in milliseconds
      loadbalancer.openstack.org/timeout-client-data: "60000"
      # Set true to enable X-Forwarded-For Headers for HTTP
      loadbalancer.openstack.org/x-forwarded-for: "false"
    loadbalancerIP: null

  deployment:
    replicas: 3
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  basicAuth:
    # htpasswd format - generate with: htpasswd -nb <user> <password>
    # !!!SENSITIVE!!! encrypt it with sops!
    credentials: "foo"

    enabled: true
    prometheus:
      enabled: true
      routeName: kube-prometheus-stack-prometheus-main
    alertmanager:
      enabled: false
      routeName: kube-prometheus-stack-alertmanager-main

gateway-helm:
  config:
    envoyGateway:
      extensionApis:
        enableBackend: true
