stfc-cloud-openstack-cluster:
    openstack-cluster:
        addons:
            monitoring:
                basicAuth: ENC[AES256_GCM,data:5LATc30QLgH7+7gJsBJwGdpfANKTigsSQkTnbEDne3Bt7Li+DJxVlbuXoA==,iv:qpgJ28Thbs/kMzzdoe+RaJE9oQ+f7RhMFFK5W6nyhVs=,tag:O0xqZX/lKmKjTHuZtQ1nVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xr298hh8ammzethfcdeh72c25wnrk3u2zlzxx78k4nfcq2rwpgqs9hljq8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RnhlV2pkYlljcDFhOXE0
            aTlCaGxwN0tCMERESmhaalB2dE9sazlSTkJnCktkS1hwZ0pZRU5CNHZDYXZoS0lm
            VHE1czY0QlRJWWF1T1lUMkFhTGNVeXMKLS0tIHlici9yVTlBbXhVMkZFT2ZvQkxa
            YnhBUGRSZkdkSXhBZjI2QWpuNml5TFEKuQIzMHbABlpL9x1KZO6eTdO5/R+0loDn
            OsHik0ohGlvHpVabvK7uwXLFz0ZGAVUCF+g9oj8ZdtpFPlxHiRn0nQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1acqcungzwkt807d3jt94ngtdt0vhk9kec4ps4a22cpaah57jw4xsl7q4xc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Z3Z4RWZRNHdPNEtiSG81
            MGpvQXFDZnRzM3RoTUMyMk4zbXRrOGhIZmlrCldQUjZvNlhkaWM2T1hqUGRHTVh4
            R2k5bDQ4QW9nQ0hqTjQzZ2lnZnNBWGcKLS0tIGgvRURQaXJZaThNUE0rMmNqTWhE
            eFJZeEIxOFFPTXhTZDBGeHZ1Rm9xeUUKU9d6IDK5P/5EF/pdjbUJH3WXZ1CG67+d
            Vw316fsaTJwYYjj7mfpy5woh96uaefqoJ5IsVEEWT22Zevi8Z6jB8g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h3dmygqf4v6jg3nxk5sr9jkp27w3q83sqnqxdd5n92xf3w6fs5kshakrxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZlpwZ203Rld1VVREMTk3
            Q0FBVDdMSFdaczNDelJEMk1SOC9QL0pFWG1rClZ1UzJXa1kwTjlMbHVwRW5UVzRB
            Yko2ZktyRXNEOWVyYkg3WGVXclUxNmMKLS0tIDg0RWVJODdMVm51SktSWEZsZlY3
            UVdpY09yeXpWTi9LOU1XMjJjWkIwN2MK28xZXX5Plc6Oaiqc5zYOUZx4hhQsNB9m
            ens9cZKwvK+LdghWB8QFs9gGE/JhfAJZVmLf/ZAOqm7KvpXMkDmq7w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12khufkd7z25eqgpjjyy0zcrq6kpjxzekmff5zhq7q54tajm4e58qul35x0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMKzc3VURMWFVvRTFzeUwz
            eU4rc0hqS1dUYjNPVGpSeU0vQjVOajJpMWxzCmZySXh0S2Nla3I1K29VZ2M5ZDV4
            MW5RaEE3SUZqVmF0dUtqOGNxVHluV0UKLS0tIFI1OG9HUUgwa2syR3pkaGNUellx
            dk9KdkdKTmJQWDBua2xEZ3dVdjNmM2MKcbqw7V2Pun4twM16EcjkrTycO/D9zXcw
            gvEmwYQI6ZYac7diRPtiSeH7UKfwLJJ8Rub9ViC+xzbCq7w0s+a+3g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16fufeddr0arrns268526gxethxgkh3g0euf8cn37kuwfmq3h23psutz4q8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuekkvLzBLY2gydTV0OEVX
            OE16WngrOVpVYURrREVxOUNiTVpWZ1JNemljCnpwS0N6aGVZeG5WZS9ncUIyRWxG
            Tk5ySW5nWC9VbXpBM3JMMWp1NjRCMUkKLS0tIHRUUndQUHhrTGtXbXNyVG5iV2VQ
            VUVVS29waWNOTkVseEM3WldLQXc1cmcKc9Kq/sUsBWduApxCybQiiniaiHMsSwEj
            pftgWYqK03zWTSxe6y7qVhmrEHzuxAw7INTtHcgu9LgddVDnH8JYLw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1a8e4gxw67kp27s3hssfxyem3e8jwaha3huz0sttfngeu60pk5pxqkfpg3d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIaFBxQW14VlA4d08rbDJZ
            bXZlTXRJWjIzRGZ2ODdvMnZyTHFEbzU2WkdjCkFmQ2J3L2pOOUJVTlRYa0s3UERt
            ekhBaHBORytWVm5vRTB3RmtZbzZONVEKLS0tIG1ORWl4RXdVNW5rOE9FQVpMVGwv
            dUVwMmhzOHZoUVpzTWh1ZTRnOGNuQkkKv2LEhdNA5eD/pJeHHH5k9aXf9H4YgMke
            D8Vpu40T1XYhikx6IXbmA3/Wke2Gj0zl3gfLUSytvoYMU3DeADaQtQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1drky6caal0j2x58yzpw9tyflcpdpmcjqy8nss7zfvspszg0xfpdsyzu8s4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmN0ZHV0QwVjFJUDRoTTlv
            UTBFVWpYUHU3M3JvcHJpOWUxQXpBbGVVZUV3CkE3SkFNZnRIalFuaElWTkZrQVll
            a1o5VGVVMXhSZ1dndzczVm9CSW9URmMKLS0tIEtKazV0Wmc2QUNIZjhMR1BTY21s
            MENLYktZSGdmZFBrTDA3cmMwRGVBRGcK8yWMNC3L5XTbPzsfBPibld89EigO971B
            VCfGOWOepNdxWOX3+ZASkj0ibckedpibcjymgALRGZiXGNBlR/JIzQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1m57vjw60dpr02ghka8kh2xlqsa0ggxauau2y488zdh89vu760qgqh8lcge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDYmJRZ0NHelU0bDB6WHRp
            bUVmeFdXMTdpWG84YU1wUmoyei9FM3lKZ0dFCktxY0RDaTZ3UTB4aFN0WlIwT25P
            Y3YrMlNUNmwweWxDR2MxSk4rTnhYSDgKLS0tIDVmb3ZhSUc0OTlBSlZ3N3h6WDI2
            WWphYjNlL3EybkJrQWJ5ZWozby93M1kKLZkfaiWvIJWkev0On+LDQIBDI7H1nLh/
            aY1eSkwNfHpQPTguqw96d8fF1C/GF5BIMeKG8RRAcGaxHKHMuXj+gA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cmq75nz6rxancqlj7g7r2pum8c9xlznuetslmjmthk2g9p4flgdqz0tv8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVYW5qRGYrMGZEc3Fpbjhv
            ZllRbVlmK2krb2w0ZThvc2trU0JRV2h6K0JZCjVFYlprNDRkc20xeVlEeUdIUTRU
            UzNOOGNsM0ZIb3NyTlU5SGNYSHB1NzgKLS0tIGpDOTd1MWxyWlNkUG5RZFJOaHc4
            d0F3TUw1VVJqa25YSm53bTJpanQrTU0KuPV5CGjK57edAPBwMIe37Q2YOm4/lABC
            zOpls19M76vK1uU5z/wv4xtA7Nqp6RTbAyErpCuCJCaULeGH7jEOIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-17T12:28:06Z"
    mac: ENC[AES256_GCM,data:ayue8qjL5N7HdZFYou+bTsJ/uQSUlM8i8hWL2m9n0Uj2y7oNMItiDSp4J1Ls73tF4MyRqJxuGIqH1MLWWS5sDAe9/JoU0rnC8Ys0stPGjvyuKz2bTxXJBwnPw6fk1H1QBDvzd0nL6XmXB0OkBq+aqg7R8P8+PY9fl+oQi2oAU0k=,iv:K5L57JoURczJ8opApshsgNRiWAFPfvyr3FJJPfDOBMo=,tag:YxcfzHjdF5B1ThlufF9Q8A==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.0
