apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-deployed-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/stfc/cloud-deployed-apps.git
    targetRevision: main
    path: clusters/staging/worker
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true

---

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: staging-worker-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=invalid"]
  generators:
    - list:
        elements:
          - name: "argocd"
            chartName: argocd

            # NOTE: each chart needs a valuesFile for this to work
            # so create one for each chart - even if its empty

            # argocd and all dependencies use the same file "argocd-setup-values.yaml"
            valuesFile: ../../../clusters/staging/worker/argocd-setup-values.yaml
            namespace: argocd

          - name: "cert-manager"
            chartName: cert-manager
            namespace: cert-manager
            valuesFile: ../../../clusters/staging/worker/argocd-setup-values.yaml

          - name: cluster-api-addon-provider
            chartName: cluster-api-addon-provider
            namespace: clusters
            valuesFile: ../../../clusters/staging/worker/argocd-setup-values.yaml

          - name: ingress-nginx-external
            chartName: nginx-external
            namespace: ingress-nginx-external
            valuesFile: ../../../clusters/staging/worker/ingress-nginx-external-values.yaml

          - name: manila-csi
            chartName: manila-csi
            namespace: manila-csi
            valuesFile: ../../../clusters/staging/worker/argocd-setup-values.yaml
            secretsFile: ../../../clusters/staging/worker/secrets/apps/manila-csi.yaml

          - name: victoria-metrics
            chartName: victoria-metrics
            namespace: victoria-metrics
            valuesFile: ../../../clusters/staging/worker/vicmet-values.yaml

          - name: longhorn
            chartName: longhorn
            namespace: longhorn-system
            valuesFile: ../../../clusters/staging/worker/argocd-setup-values.yaml

          - name: materials-galaxy
            chartName: materials-galaxy
            namespace: materials-galaxy
            valuesFile: ../../../clusters/staging/worker/materials-galaxy-values.yaml
            secretsFile: ../../../clusters/staging/worker/secrets/apps/materials-galaxy.yaml

          - name: harbor
            chartName: harbor
            namespace: harbor
            secretsFile: ../../../clusters/staging/worker/secrets/apps/harbor.yaml
            valuesFile: ../../../clusters/staging/worker/harbor-values.yaml

          - name: rabbit-consumer
            chartName: rabbit-consumer
            namespace: rabbit-consumer
            valuesFile: ../../../clusters/staging/worker/rabbit-consumer-values.yaml

          - name: opensearch
            chartName: opensearch
            namespace: opensearch
            valuesFile: ../../../clusters/staging/worker/opensearch-values.yaml
            secretsFile: ../../../clusters/staging/worker/secrets/apps/opensearch.yaml

          - name: docker-registry
            chartName: docker-registry
            namespace: docker-registry
            valuesFile: ../../../clusters/staging/worker/docker-registry-values.yaml
            secretsFile: ../../../clusters/staging/worker/secrets/apps/docker-registry.yaml

  syncPolicy:
    # Don't remove everything if we remove the appset
    preserveResourcesOnDeletion: true

  template:
    metadata:
      name: "{{.name}}"
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: "https://github.com/stfc/cloud-deployed-apps.git"
        targetRevision: main
        path: "charts/staging/{{.chartName}}"
        helm:
          valueFiles:
            - '{{.valuesFile | default "../../../clusters/_shared/dummy.yaml"}}'
            - secrets://{{ .secretsFile | default "../../../clusters/_shared/dummy.yaml"}}

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.namespace}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true

      # ignore outofsync issues with longhorn CRDs with "preserveUnknownField"
      # https://github.com/argoproj/argo-cd/issues/6401#issuecomment-854995249
      ignoreDifferences:
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        jsonPointers:
        - /spec/preserveUnknownFields

  templatePatch: |
    {{- if eq .name "manila-csi" }}
      spec:
        ignoreDifferences:
          - group: rbac.authorization.k8s.io
            kind: ClusterRole
            name: manila-csi-openstack-manila-csi-controllerplugin
            jsonPointers:
              - /rules
          - group: rbac.authorization.k8s.io
            kind: ClusterRole
            name: manila-csi-openstack-manila-csi-nodeplugin
            jsonPointers:
              - /rules
    {{- end }}
