argo-cd:
  httproute:
    hostnames:
      - argocd.staging-mgmt.nubes.stfc.ac.uk
    parentRefs:
      - name: internal-gateway
        namespace: envoy-gateway-system
        sectionName: https
  global:
    domain: argocd.staging-worker.nubes.stfc.ac.uk

stfc-cloud-longhorn:
  longhorn:
    httproute:
      enabled: true
      parentRefs:
        - name: internal-gateway
          namespace: envoy-gateway-system
          sectionName: https
      hostnames:
        - longhorn.staging-worker.nubes.stfc.ac.uk

    persistence:
      # can't be set for RWX
      migratable: false

stfc-cloud-cert-manager:
  le-staging:
    enabled: true
    ingressClassName: ingress-nginx-external

  le-prod:
    email: cloud-support@stfc.ac.uk
    enabled: true
    ingressClassName: ingress-nginx-external
