argo-cd:
  server:
    httproute:
      enabled: true
      hostnames:
        - argocd.staging-worker.nubes.stfc.ac.uk
      parentRefs:
        - name: envoy-gateway-internal
          namespace: envoy-gateway-system
          sectionName: staging-internal-https

  global:
    domain: argocd.staging-worker.nubes.stfc.ac.uk

stfc-cloud-longhorn:
  longhorn:
    httproute:
      enabled: true
      parentRefs:
        - name: envoy-gateway-internal
          namespace: envoy-gateway-system
          sectionName: staging-internal-https
      hostnames:
        - longhorn.staging-worker.nubes.stfc.ac.uk

    persistence:
      # can't be set for RWX
      migratable: false

stfc-cloud-cert-manager:
  le-staging:
    enabled: true
    ingressClassName: ingress-nginx-external

  le-prod:
    email: cloud-support@stfc.ac.uk
    enabled: true
    ingressClassName: ingress-nginx-external
