stfc-cloud-argocd:
  argo-cd:
    configs:
      cm:
        # TODO remove this once PR merged
        oidc.skip.insecure.verify: false

    server:
      httproute:
        enabled: true
        hostnames:
          - argocd.staging-worker.nubes.stfc.ac.uk
        parentRefs:
          - name: envoy-gateway-internal
            namespace: envoy-gateway-system
            sectionName: https
            group: gateway.networking.k8s.io
            kind: Gateway
    global:
      domain: argocd.staging-worker.nubes.stfc.ac.uk

stfc-cloud-longhorn:
  longhorn:
    httproute:
      parentRefs:
        - name: envoy-gateway-internal
          namespace: envoy-gateway-system
          sectionName: https
          group: gateway.networking.k8s.io
          kind: Gateway
      hostnames:
        - longhorn.staging-worker.nubes.stfc.ac.uk

    persistence:
      # can't be set for RWX
      migratable: false

stfc-cloud-cert-manager:
  clusterIssuers:
    - name: external-le-staging
      type: le-staging
      email: cloud-support@stfc.ac.uk
      gateway:
        name: envoy-gateway-external
        namespace: envoy-gateway-system

    - name: external-le-prod
      type: le-prod
      email: cloud-support@stfc.ac.uk
      gateway:
        name: envoy-gateway-external
        namespace: envoy-gateway-system
