stfc-cloud-docker-registry:
  replicaCount: 3

  ingress:
    enabled: true
    ingressClassName: ingress-nginx-harbor
    path: /
    # Used to create an Ingress record.
    annotations: 
      kubernetes.io/ingress.class: ingress-nginx-harbor
      cert-manager.io/cluster-issuer: "self-signed"  
    hosts:
      - staging.dockerhub.stfc.ac.uk
    tls:
      - hosts:
        - staging.dockerhub.stfc.ac.uk

  # we'll default to S3
  persistence:
    enabled: false

  # set the type of filesystem to use: filesystem or s3
  storage: s3

  # Options for s3 storage type if .Values.storage=s3:
  s3:
    bucket: staging-registry
    regionEndpoint: s3.echo.stfc.ac.uk


  ## Pass extra environment variables to the Docker Registry container.
  extraEnvVars:
  # - name: EXTRA_VAR_1
  #  value: extra-var-value-1
  # - name: EXTRA_VAR_2
  #   value: extra-var-value-2

  # remote url for pull-through cache 
  proxy:
    remoteURL: https://registry-1.docker.io

  metrics:
    enabled: false
    # Create a prometheus-operator servicemonitor
    serviceMonitor:
      enabled: false

  # Config to pass to 
  configData:
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3