stfc-cloud-docker-registry:
  httproute:
    hostnames:
      - staging.dockerhub.stfc.ac.uk
    parentRefs:
      - name: envoy-gateway-external
        namespace: envoy-gateway-system
        sectionName: dockerhub-https
        group: gateway.networking.k8s.io
        kind: Gateway

  # Options for s3 storage type if .Values.storage=s3:
  s3:
    bucket: staging-registry
    regionEndpoint: https://s3.echo.stfc.ac.uk
    forcepathstyle: true
    skipverify: false
