external:
  enabled: true
  # change to lets-encrypt once we know it works
  clusterIssuerName: self-signed
  service:
    loadBalancerIP: 130.246.81.227

  listeners:
    - name: harbor-https
      protocol: HTTPS
      port: 443
      tlsSecret: harbor-tls
      hostname: "staging.harbor.stfc.ac.uk"
      allowedRoutes:
        namespaces:
          from: All

    - name: dockerhub-https
      protocol: HTTPS
      port: 443
      tlsSecret: dockerhub-tls
      hostname: "staging.dockerhub.stfc.ac.uk"
      allowedRoutes:
        namespaces:
          from: All

internal:
  clusterIssuerName: self-signed

  service:
    loadBalancerIP: 130.246.81.242

  listeners:
    # for all internal services - share the same tls
    # we don't need separate listeners since we use self-signed certs
    - name: staging-internal-https
      protocol: HTTPS
      port: 443
      tlsSecret: self-signed-tls-secret
      hostname: "*.staging-worker.nubes.stfc.ac.uk"
      allowedRoutes:
        namespaces:
          from: All

basicAuth:
  alertmanager:
    enabled: true
