stfc-cloud-harbor:
  harbor:
    externalURL: "https://staging.harbor.stfc.ac.uk"

    expose:
      route:
        enabled: true
        parentRefs:
          - name: envoy-gateway-external
            namespace: envoy-gateway-system
            sectionName: harbor-https
            group: gateway.networking.k8s.io
            kind: Gateway
        hosts:
          - "staging.harbor.stfc.ac.uk"

    database:
      type: external
      external:
        host: "dbspgha03.fds.rl.ac.uk"
        coreDatabase: "cloud_harbor_registry_dev"

    persistence:
      imageChartStorage:
        s3:
          bucket: new-staging-harbor
          regionendpoint: s3.echo.stfc.ac.uk

  backup:
    sourceBucket: "s3://new-staging-harbor"
    destination:
      daily: "s3://staging-harbor-backup/daily"
      weekly: "s3://staging-harbor-backup/weekly"
      monthly: "s3://staging-harbor-backup/monthly"
    endpoint: "https://s3.echo.stfc.ac.uk"

  #  certificate:
  #    expose:
  #      issuer:
  #        name: external-le-prod
