stfc-cloud-openstack-cluster:
  openstack-cluster:
    cloudCredentialsSecretName: staging-worker-cluster-cloud-credentials
    registryMirrors: { docker.io: ["https://staging.dockerhub.stfc.ac.uk/v2/"] }

    controlPlane:
      machineFlavor: dep-l2.tiny

    nodeGroups:
      - name: default-md-0
        machineCount: 5
        machineFlavor: dep-l2.xsmall

    nodeGroupDefaults:
      machineFlavor: dep-l2.xsmall
      nodeLabels:
        # we're running longhorn on this cluster
        # set label so worker nodes can host longhorn volumes
        longhorn.store.nodeselect/longhorn-storage-node: true

    addons:
      monitoring:
        enabled: true
        kubePrometheusStack:
          release:
            values:
              prometheus:
                prometheusSpec:
                  externalLabels:
                    cluster: worker
                    env: staging
                route:
                  main:
                    enabled: true
                    hostnames:
                      - prometheus.staging-worker.nubes.stfc.ac.uk
                    parentRefs:
                      - name: envoy-gateway-internal
                        namespace: envoy-gateway-system
                        sectionName: staging-internal-https
                        group: gateway.networking.k8s.io
                        kind: Gateway
              grafana:
                grafana.ini:
                  server:
                    root_url: grafana.staging-worker.nubes.stfc.ac.uk
                route:
                  main:
                    enabled: true
                    hostnames:
                      - grafana.staging-worker.nubes.stfc.ac.uk
                    parentRefs:
                      - name: envoy-gateway-internal
                        namespace: envoy-gateway-system
                        sectionName: staging-internal-https
                        group: gateway.networking.k8s.io
                        kind: Gateway
              alertmanager:
                enabled: true
                route:
                  main:
                    enabled: true
                    hostnames:
                      - alertmanager.staging-worker.nubes.stfc.ac.uk
                    parentRefs:
                      - name: envoy-gateway-internal
                        namespace: envoy-gateway-system
                        sectionName: staging-internal-https
                        group: gateway.networking.k8s.io
                        kind: Gateway
      etcdDefrag:
        release:
          values:
            schedule: 10 12 * * * # smearing the time for defrag job 10:12am daily
