stfc-cloud-openstack-cluster:
  openstack-cluster:
    cloudCredentialsSecretName: staging-worker-cluster-cloud-credentials
    registryMirrors: { docker.io: ["https://staging.dockerhub.stfc.ac.uk/v2/"] }

    controlPlane:
      machineFlavor: dep-l2.tiny

    nodeGroups:
      - name: default-md-0
        machineCount: 5
        machineFlavor: dep-l2.xsmall

    nodeGroupDefaults:
      machineFlavor: dep-l2.xsmall
      nodeLabels:
        # we're running longhorn on this cluster
        # set label so worker nodes can host longhorn volumes
        longhorn.store.nodeselect/longhorn-storage-node: true

    addons:
      etcdDefrag:
        release:
          values:
            schedule: 10 12 * * * # smearing the time for defrag job 10:12am daily
