apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-deployed-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/stfc/cloud-deployed-apps.git
    targetRevision: main
    path: clusters/dev/worker
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true

---

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: worker-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=invalid"]
  generators:
    - list:
        elements:
          - name: "argocd"
            chartName: argocd

            # NOTE: each chart needs a valuesFile for this to work
            # so create one for each chart - even if its empty

            # argocd and all dependencies use the same file "argocd-setup-values.yaml"
            valuesFile: ../../../clusters/dev/worker/argocd-setup-values.yaml
            namespace: argocd

          - name: "cert-manager"
            chartName: cert-manager
            namespace: cert-manager
            valuesFile: ../../../clusters/dev/worker/argocd-setup-values.yaml

          - name: longhorn
            chartName: longhorn
            namespace: longhorn-system
            valuesFile: ../../../clusters/dev/worker/argocd-setup-values.yaml

          - name: materials-galaxy
            chartName: materials-galaxy
            namespace: materials-galaxy
            valuesFile: ../../../clusters/dev/worker/materials-galaxy-values.yaml
            secretsFile: ../../../secrets/dev/worker/materials-galaxy.yaml

  syncPolicy:
    # Don't remove everything if we remove the appset
    preserveResourcesOnDeletion: true

  template:
    metadata:
      name: "{{.name}}"
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: "https://github.com/stfc/cloud-deployed-apps.git"
        targetRevision: main
        path: "charts/dev/{{.chartName}}"
        helm:
          valueFiles:
            - "{{.valuesFile}}"
            # a hack to get optional secrets working
            - secrets://{{ .secretsFile | default "../../../secrets/dummy-secret.yaml"}}
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.namespace}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
