# adapted from https://github.com/camptocamp/helm-dependency-update-action example
permissions:
  contents: read
  
name: Update Chart Dependencies on Staging

env:
  author: "${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>"
  committer: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"

on:
  schedule:
    - cron: '0 13 * * 1-5' # Every working day at 1pm UTC
  workflow_dispatch:

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - name: "Setup Github Token"
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 #v3.2.0
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        
      - name: Set up Helm
        uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 #v5.0.1
        with:
          version: 'latest'

      - name: Install yq
        uses: mikefarah/yq@c14f446382944492701b16c1ddb48bb9dbe683e3 #v4.53.6
        
      - name: Update dependencies for Staging Charts
        id: updater
        run: .github/workflows/update_charts.sh

      - name: Get current date
        if: steps.updater.outputs.updated_charts != '0'
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Set branch and PR names
        if: steps.updater.outputs.updated_charts != '0'
        id: env-vars
        run: |
          echo "pr_title=Update Helm Chart Dependencies - ${{ steps.date.outputs.date }}" >> $GITHUB_OUTPUT

      - name: Create PR with Chart updates
        if: steps.updater.outputs.updated_charts != '0'
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 #v8.1.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: "${{ steps.env-vars.outputs.pr_title }}"
          author: ${{ env.author }}
          committer: ${{ env.committer }}
          branch: update-staging-chart-deps
          delete-branch: true
          title: ${{ steps.env-vars.outputs.pr_title }}
          labels: |
            automated
            dependency-update
          body: |
            This PR updates dependencies for Helm charts under `charts/staging/*` to the latest available versions.
            - Automatically generated via GitHub Actions
          base: main
