creation_rules:
  - unencrypted_regex: "^(apiVersion|metadata|kind|type)$"
    key_groups:
      - age:
        # Temporary key for ArgoCD
        - age1pwxlgd3pzdkwudzjrx6fun8ddhgdl3m25jr24rd9wc9qh2wpkfaszccvv6
        
        # Access Keys
        # Staging Access Key
        - age1vhunptck6gfu8u2uwrymx6ud0jgwxxjmn0rqh4hftfma6wxjrf6sgdg7dz
